/*

 * DO NOT EDIT!

 *

 * This file was generated by the Breeze XML Studio Java Export Wizard.

 *

 *        Project: connectship

 *     Class Name: COMMODITYCONTENTS

 *           Date: Fri Feb 22 21:58:50 PST 2002

 * Breeze Version: 2.2.1 build 114

 *

 * IMPORTANT: Please see your Breeze license for more information on

 *            where and how this generated code may be used.

 *

 */


package com.owd.core.csXml;


import com.tbf.xml.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;


/**
 * COMMODITYCONTENTS class.
 */

public class COMMODITYCONTENTS

        implements com.tbf.xml.XmlObject, Validateable, java.io.Serializable {
private final static Logger log =  LogManager.getLogger();


    /**
     * Constant for "CONTENT" node name.
     */

    public static final String $CONTENT = "CONTENT";


    /**
     * Constant for "COMMODITYCONTENTS" node name.
     */

    public static final String $COMMODITYCONTENTS = "COMMODITYCONTENTS";


    protected java.util.Vector _CONTENT = new java.util.Vector();


    /**
     * Storage for UNEXPECTED_XML errors.
     */

    protected Vector _unexpected_xml_errors_ = null;


    /**
     * Default no args constructor.
     */

    public COMMODITYCONTENTS() {

    }


    /**
     * Creates and populates an instance from the provided parse tree.
     *
     * @param xml the parse tree
     */

    public COMMODITYCONTENTS(XmlElement xml) {

        fromXml(xml);

    }


    /**
     * Get the CONTENT property.
     */

    public java.util.Vector getCONTENT() {

        return (_CONTENT);

    }


    public CONTENT getCONTENTAt(int index)

            throws IndexOutOfBoundsException {

        return ((CONTENT) _CONTENT.elementAt(index));

    }


    /**
     * Get the count of elements in the CONTENT property.
     */

    public int getCONTENTCount() {

        if (_CONTENT == null) {

            return (0);

        }


        return (_CONTENT.size());

    }


    /**
     * Set the CONTENT property.
     */

    public void setCONTENT(java.util.Vector newList) {


        if (newList == null) {

            _CONTENT.removeAllElements();

        } else {

            _CONTENT = (java.util.Vector) newList.clone();

        }

    }


    public void addCONTENT(CONTENT obj) {

        if (obj == null) {

            return;

        }


        _CONTENT.addElement(obj);

    }


    public void setCONTENTAt(CONTENT obj, int index)

            throws IndexOutOfBoundsException {

        if (obj == null) {

            return;

        }


        _CONTENT.setElementAt(obj, index);

    }


    public void removeCONTENT(CONTENT obj) {

        if (obj == null) {

            return;

        }


        _CONTENT.removeElement(obj);

    }


    public void removeCONTENTAt(int index)

            throws IndexOutOfBoundsException {

        _CONTENT.removeElementAt(index);

    }


    protected void setCONTENT(XmlElement xml) {


        _CONTENT.removeAllElements();

        XmlElement saved_xml = xml;


        while (xml != null &&

                xml.equals(CONTENT.$CONTENT)) {

            Object obj = new CONTENT(xml);

            _CONTENT.addElement(obj);

            saved_xml.setLastProcessed(xml);

            xml = xml.next();

        }

    }


    /**
     * Gets the XML tag name for this object.
     */

    public String getXmlTagName() {

        return ($COMMODITYCONTENTS);

    }


    /**
     * Gets the XML tag name for this class.
     */

    public static String getClassXmlTagName() {

        return ($COMMODITYCONTENTS);

    }


    /**
     * This flag is used to used to check whether
     * <p/>
     * the validators have been created.
     */

    transient protected static boolean _validators_created = false;



    /*

     * XML Validators

     */

    transient protected static XmlValidator

            _CONTENT_validator_ = null;


    /**
     * Create the validators for this class.
     */

    protected static synchronized void createValidators() {


        if (_validators_created) {

            return;

        }


        _CONTENT_validator_ = new XmlValidator("COMMODITYCONTENTS.CONTENT", "Element",

                "COMMODITYCONTENTS/CONTENT", true);


        _validators_created = true;

    }


    /**
     * Checks this object to see if it will produce valid XML.
     */

    public boolean isValid() {


        if (!(this instanceof Validateable)) {

            return (true);

        }


        Vector errors = ((Validateable) this).getValidationErrors(true);

        if (errors == null || errors.size() < 1) {

            return (true);

        }


        return (false);

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     */

    public Vector getValidationErrors() {

        return (getValidationErrors(false));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error) {

        return (getValidationErrors(return_on_error, true));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error, boolean traverse) {


        createValidators();


        Vector errors;

        if (_unexpected_xml_errors_ != null &&

                _unexpected_xml_errors_.size() > 0) {

            errors = (Vector) _unexpected_xml_errors_.clone();

            if (return_on_error) {

                return (errors);

            }

        } else {

            errors = new Vector();

        }


        XmlValidationError e;


        if (!traverse) {

            if (errors.size() < 1) {

                return (null);

            }


            return (errors);

        }


        boolean is_valid;


        is_valid = _CONTENT_validator_.isValid(_CONTENT,

                errors, return_on_error, traverse);

        if (!is_valid && return_on_error) {

            return (errors);

        }


        if (errors.size() < 1) {

            return (null);

        }


        return (errors);

    }


    /**
     * Checks the XML to see whether it matches the
     * <p/>
     * XML contents of this class.
     */

    public static boolean matches(XmlElement xml) {


        if (xml == null) {

            return (false);

        }


        return (xml.equals($COMMODITYCONTENTS));

    }


    /**
     * This method unmarshals an XML document instance
     * <p/>
     * into an instance of this class.
     */

    public static COMMODITYCONTENTS unmarshal(InputStream in) throws Exception {


        COMMODITYCONTENTS obj = new COMMODITYCONTENTS();

        ObjectFactory.unmarshal(obj, in);

        return (obj);

    }


    /**
     * Populates this object with the values from the
     * <p/>
     * parsed XML.
     */

    public void fromXml(XmlElement xml) {


        if (xml == null) {

            return;

        }


        if (!xml.equals($COMMODITYCONTENTS)) {

            return;

        }





        /*

         * Get the contained XmlElement, this is what we process

         */

        xml = xml.getSubElementAt(0);

        if (xml == null) {

            return;

        }


        if (xml.equals($CONTENT)) {

            setCONTENT(xml);

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml != null) {


            _unexpected_xml_errors_ =

                    XmlValidationError.addUnexpectedXmlError(this, _unexpected_xml_errors_, xml);

            xml = xml.next();

        }

    }


    /**
     * This method marshals this object into an
     * <p/>
     * XML instance document.
     */

    public void marshal(OutputStream out) {

        toXml(out);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream) {

        toXml(stream, true);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream, String indent, boolean embed_files) {


        if (stream instanceof XmlOutputStream) {

            toXml(stream, embed_files);

        } else {

            FormattedOutputStream out =

                    new FormattedOutputStream(stream);

            out.setIndentString(indent);

            toXml(out, embed_files);

        }

    }


    /**
     * Serializes this object to XML.
     */

    public void toXml(OutputStream stream, boolean embed_files) {


        XmlOutputStream out = null;

        if (stream instanceof XmlOutputStream) {

            out = (XmlOutputStream) stream;

        } else {

            out = new RawOutputStream(stream);

        }


        out.writeStartTag(getXmlTagName(), false);

        out.incrementIndent();


        out.write(null,

                getCONTENT(), embed_files);


        out.decrementIndent();

        out.writeEndTag(getXmlTagName());

    }


    /**
     * Get the  birth certificate for this object.
     */

    public String birthCertificate() {

        return ("1hge137:cy11q2li:17gbvej");

    }

}
