/*

 * DO NOT EDIT!

 *

 * This file was generated by the Breeze XML Studio Java Export Wizard.

 *

 *        Project: connectship

 *     Class Name: DOCUMENTREQUEST

 *           Date: Tue Jun 18 01:10:31 PDT 2002

 * Breeze Version: 2.2.1 build 114

 *

 * IMPORTANT: Please see your Breeze license for more information on

 *            where and how this generated code may be used.

 *

 */


package com.owd.core.csXml;


import com.tbf.xml.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;


/**
 * DOCUMENTREQUEST class.
 */

public class DOCUMENTREQUEST

        implements com.tbf.xml.XmlObject, Validateable, java.io.Serializable {
private final static Logger log =  LogManager.getLogger();


    /**
     * Constant for "DOCUMENTREQUEST" node name.
     */

    public static final String $DOCUMENTREQUEST = "DOCUMENTREQUEST";


    /**
     * Constant for "SHIPMENT" node name.
     */

    public static final String $SHIPMENT = "SHIPMENT";


    /**
     * Constant for "LOGIN" node name.
     */

    public static final String $LOGIN = "LOGIN";


    protected LOGIN _LOGIN = null;

    protected java.util.Vector _SHIPMENT = new java.util.Vector();


    /**
     * Storage for UNEXPECTED_XML errors.
     */

    protected Vector _unexpected_xml_errors_ = null;


    /**
     * Default no args constructor.
     */

    public DOCUMENTREQUEST() {

    }


    /**
     * Creates and populates an instance from the provided parse tree.
     *
     * @param xml the parse tree
     */

    public DOCUMENTREQUEST(XmlElement xml) {

        fromXml(xml);

    }


    /**
     * Get the LOGIN property.
     */

    public LOGIN getLOGIN() {

        return (_LOGIN);

    }


    /**
     * Set the LOGIN property.
     */

    public void setLOGIN(LOGIN obj) {

        _LOGIN = obj;

    }


    protected void setLOGIN(XmlElement xml) {


        _LOGIN =

                new LOGIN(xml);

    }


    /**
     * Checks for whether LOGIN is set or not.
     *
     * @returns true if LOGIN is set, false if not
     */

    public boolean hasLOGIN() {

        return (_LOGIN != null);

    }


    /**
     * Discards LOGIN's value.
     */

    public void deleteLOGIN() {

        _LOGIN = null;

    }


    /**
     * Get the SHIPMENT property.
     */

    public java.util.Vector getSHIPMENT() {

        return (_SHIPMENT);

    }


    public SHIPMENT getSHIPMENTAt(int index)

            throws IndexOutOfBoundsException {

        return ((SHIPMENT) _SHIPMENT.elementAt(index));

    }


    /**
     * Get the count of elements in the SHIPMENT property.
     */

    public int getSHIPMENTCount() {

        if (_SHIPMENT == null) {

            return (0);

        }


        return (_SHIPMENT.size());

    }


    /**
     * Set the SHIPMENT property.
     */

    public void setSHIPMENT(java.util.Vector newList) {


        if (newList == null) {

            _SHIPMENT.removeAllElements();

        } else {

            _SHIPMENT = (java.util.Vector) newList.clone();

        }

    }


    public void addSHIPMENT(SHIPMENT obj) {

        if (obj == null) {

            return;

        }


        _SHIPMENT.addElement(obj);

    }


    public void setSHIPMENTAt(SHIPMENT obj, int index)

            throws IndexOutOfBoundsException {

        if (obj == null) {

            return;

        }


        _SHIPMENT.setElementAt(obj, index);

    }


    public void removeSHIPMENT(SHIPMENT obj) {

        if (obj == null) {

            return;

        }


        _SHIPMENT.removeElement(obj);

    }


    public void removeSHIPMENTAt(int index)

            throws IndexOutOfBoundsException {

        _SHIPMENT.removeElementAt(index);

    }


    protected void setSHIPMENT(XmlElement xml) {


        _SHIPMENT.removeAllElements();

        XmlElement saved_xml = xml;


        while (xml != null &&

                xml.equals(SHIPMENT.$SHIPMENT)) {

            Object obj = new SHIPMENT(xml);

            _SHIPMENT.addElement(obj);

            saved_xml.setLastProcessed(xml);

            xml = xml.next();

        }

    }


    /**
     * Gets the XML tag name for this object.
     */

    public String getXmlTagName() {

        return ($DOCUMENTREQUEST);

    }


    /**
     * Gets the XML tag name for this class.
     */

    public static String getClassXmlTagName() {

        return ($DOCUMENTREQUEST);

    }


    /**
     * This flag is used to used to check whether
     * <p/>
     * the validators have been created.
     */

    transient protected static boolean _validators_created = false;



    /*

     * XML Validators

     */

    transient protected static XmlValidator

            _LOGIN_validator_ = null;

    transient protected static XmlValidator

            _SHIPMENT_validator_ = null;


    /**
     * Create the validators for this class.
     */

    protected static synchronized void createValidators() {


        if (_validators_created) {

            return;

        }


        _LOGIN_validator_ = new XmlValidator("DOCUMENTREQUEST.LOGIN", "Element",

                "DOCUMENTREQUEST/LOGIN", true);


        _SHIPMENT_validator_ = new XmlValidator("DOCUMENTREQUEST.SHIPMENT", "Element",

                "DOCUMENTREQUEST/SHIPMENT", true);


        _validators_created = true;

    }


    /**
     * Checks this object to see if it will produce valid XML.
     */

    public boolean isValid() {


        if (!(this instanceof Validateable)) {

            return (true);

        }


        Vector errors = ((Validateable) this).getValidationErrors(true);

        if (errors == null || errors.size() < 1) {

            return (true);

        }


        return (false);

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     */

    public Vector getValidationErrors() {

        return (getValidationErrors(false));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error) {

        return (getValidationErrors(return_on_error, true));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error, boolean traverse) {


        createValidators();


        Vector errors;

        if (_unexpected_xml_errors_ != null &&

                _unexpected_xml_errors_.size() > 0) {

            errors = (Vector) _unexpected_xml_errors_.clone();

            if (return_on_error) {

                return (errors);

            }

        } else {

            errors = new Vector();

        }


        XmlValidationError e;


        if (!traverse) {

            if (errors.size() < 1) {

                return (null);

            }


            return (errors);

        }


        boolean is_valid;


        is_valid = _LOGIN_validator_.isValid(_LOGIN,

                errors, return_on_error, traverse);

        if (!is_valid && return_on_error) {

            return (errors);

        }


        is_valid = _SHIPMENT_validator_.isValid(_SHIPMENT,

                errors, return_on_error, traverse);

        if (!is_valid && return_on_error) {

            return (errors);

        }


        if (errors.size() < 1) {

            return (null);

        }


        return (errors);

    }


    /**
     * Checks the XML to see whether it matches the
     * <p/>
     * XML contents of this class.
     */

    public static boolean matches(XmlElement xml) {


        if (xml == null) {

            return (false);

        }


        return (xml.equals($DOCUMENTREQUEST));

    }


    /**
     * This method unmarshals an XML document instance
     * <p/>
     * into an instance of this class.
     */

    public static DOCUMENTREQUEST unmarshal(InputStream in) throws Exception {


        DOCUMENTREQUEST obj = new DOCUMENTREQUEST();

        ObjectFactory.unmarshal(obj, in);

        return (obj);

    }


    /**
     * Populates this object with the values from the
     * <p/>
     * parsed XML.
     */

    public void fromXml(XmlElement xml) {


        if (xml == null) {

            return;

        }


        if (!xml.equals($DOCUMENTREQUEST)) {

            return;

        }





        /*

         * Get the contained XmlElement, this is what we process

         */

        xml = xml.getSubElementAt(0);

        if (xml == null) {

            return;

        }


        if (xml.equals($LOGIN)) {

            setLOGIN(xml);

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($SHIPMENT)) {

            setSHIPMENT(xml);

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml != null) {


            _unexpected_xml_errors_ =

                    XmlValidationError.addUnexpectedXmlError(this, _unexpected_xml_errors_, xml);

            xml = xml.next();

        }

    }


    /**
     * This method marshals this object into an
     * <p/>
     * XML instance document.
     */

    public void marshal(OutputStream out) {

        toXml(out);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream) {

        toXml(stream, true);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream, String indent, boolean embed_files) {


        if (stream instanceof XmlOutputStream) {

            toXml(stream, embed_files);

        } else {

            FormattedOutputStream out =

                    new FormattedOutputStream(stream);

            out.setIndentString(indent);

            toXml(out, embed_files);

        }

    }


    /**
     * Serializes this object to XML.
     */

    public void toXml(OutputStream stream, boolean embed_files) {


        XmlOutputStream out = null;

        if (stream instanceof XmlOutputStream) {

            out = (XmlOutputStream) stream;

        } else {

            out = new RawOutputStream(stream);

        }


        out.writeStartTag(getXmlTagName(), false);

        out.incrementIndent();


        Object LOGIN_value = getLOGIN();

        if (LOGIN_value instanceof XmlObject) {

            out.write(null,

                    (XmlObject) LOGIN_value,

                    embed_files);

        }

        out.write(null,

                getSHIPMENT(), embed_files);


        out.decrementIndent();

        out.writeEndTag(getXmlTagName());

    }


    /**
     * Get the  birth certificate for this object.
     */

    public String birthCertificate() {

        return ("1hge1fs:d2li2dy0:1wnjdzn");

    }

}
