/*

 * DO NOT EDIT!

 *

 * This file was generated by the Breeze XML Studio Java Export Wizard.

 *

 *        Project: connectship

 *     Class Name: ERRORSTATUS_1

 *           Date: Fri Feb 22 21:58:51 PST 2002

 * Breeze Version: 2.2.1 build 114

 *

 * IMPORTANT: Please see your Breeze license for more information on

 *            where and how this generated code may be used.

 *

 */


package com.owd.core.csXml;


import com.tbf.xml.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;


/**
 * ERRORSTATUS_1 class.
 */

public class ERRORSTATUS_1

        implements com.tbf.xml.XmlObject, Validateable, java.io.Serializable {
private final static Logger log =  LogManager.getLogger();


    /**
     * Constant for "ERRORSTATUS" node name.
     */

    public static final String $ERRORSTATUS = "ERRORSTATUS";


    /**
     * Constant for "DOCSTATUS" node name.
     */

    public static final String $DOCSTATUS = "DOCSTATUS";


    /**
     * Constant for "EMAILSTATUS" node name.
     */

    public static final String $EMAILSTATUS = "EMAILSTATUS";


    /**
     * Constant for "HTMLSTATUS" node name.
     */

    public static final String $HTMLSTATUS = "HTMLSTATUS";


    protected DOCSTATUS _DOCSTATUS = null;

    protected HTMLSTATUS _HTMLSTATUS = null;

    protected EMAILSTATUS _EMAILSTATUS = null;


    /**
     * Storage for UNEXPECTED_XML errors.
     */

    protected Vector _unexpected_xml_errors_ = null;


    /**
     * Default no args constructor.
     */

    public ERRORSTATUS_1() {

    }


    /**
     * Creates and populates an instance from the provided parse tree.
     *
     * @param xml the parse tree
     */

    public ERRORSTATUS_1(XmlElement xml) {

        fromXml(xml);

    }


    /**
     * Get the DOCSTATUS property.
     */

    public DOCSTATUS getDOCSTATUS() {

        return (_DOCSTATUS);

    }


    /**
     * Set the DOCSTATUS property.
     */

    public void setDOCSTATUS(DOCSTATUS obj) {

        _DOCSTATUS = obj;

    }


    protected void setDOCSTATUS(XmlElement xml) {


        _DOCSTATUS =

                new DOCSTATUS(xml);

    }


    /**
     * Checks for whether DOCSTATUS is set or not.
     *
     * @returns true if DOCSTATUS is set, false if not
     */

    public boolean hasDOCSTATUS() {

        return (_DOCSTATUS != null);

    }


    /**
     * Discards DOCSTATUS's value.
     */

    public void deleteDOCSTATUS() {

        _DOCSTATUS = null;

    }


    /**
     * Get the HTMLSTATUS property.
     */

    public HTMLSTATUS getHTMLSTATUS() {

        return (_HTMLSTATUS);

    }


    /**
     * Set the HTMLSTATUS property.
     */

    public void setHTMLSTATUS(HTMLSTATUS obj) {

        _HTMLSTATUS = obj;

    }


    protected void setHTMLSTATUS(XmlElement xml) {


        _HTMLSTATUS =

                new HTMLSTATUS(xml);

    }


    /**
     * Checks for whether HTMLSTATUS is set or not.
     *
     * @returns true if HTMLSTATUS is set, false if not
     */

    public boolean hasHTMLSTATUS() {

        return (_HTMLSTATUS != null);

    }


    /**
     * Discards HTMLSTATUS's value.
     */

    public void deleteHTMLSTATUS() {

        _HTMLSTATUS = null;

    }


    /**
     * Get the EMAILSTATUS property.
     */

    public EMAILSTATUS getEMAILSTATUS() {

        return (_EMAILSTATUS);

    }


    /**
     * Set the EMAILSTATUS property.
     */

    public void setEMAILSTATUS(EMAILSTATUS obj) {

        _EMAILSTATUS = obj;

    }


    protected void setEMAILSTATUS(XmlElement xml) {


        _EMAILSTATUS =

                new EMAILSTATUS(xml);

    }


    /**
     * Checks for whether EMAILSTATUS is set or not.
     *
     * @returns true if EMAILSTATUS is set, false if not
     */

    public boolean hasEMAILSTATUS() {

        return (_EMAILSTATUS != null);

    }


    /**
     * Discards EMAILSTATUS's value.
     */

    public void deleteEMAILSTATUS() {

        _EMAILSTATUS = null;

    }


    /**
     * Gets the XML tag name for this object.
     */

    public String getXmlTagName() {

        return ($ERRORSTATUS);

    }


    /**
     * Gets the XML tag name for this class.
     */

    public static String getClassXmlTagName() {

        return ($ERRORSTATUS);

    }


    /**
     * This flag is used to used to check whether
     * <p/>
     * the validators have been created.
     */

    transient protected static boolean _validators_created = false;



    /*

     * XML Validators

     */

    transient protected static XmlValidator

            _DOCSTATUS_validator_ = null;

    transient protected static XmlValidator

            _HTMLSTATUS_validator_ = null;

    transient protected static XmlValidator

            _EMAILSTATUS_validator_ = null;


    /**
     * Create the validators for this class.
     */

    protected static synchronized void createValidators() {


        if (_validators_created) {

            return;

        }


        _DOCSTATUS_validator_ = new XmlValidator("ERRORSTATUS_1.DOCSTATUS", "Element",

                "ERRORSTATUS/DOCSTATUS", true);


        _HTMLSTATUS_validator_ = new XmlValidator("ERRORSTATUS_1.HTMLSTATUS", "Element",

                "ERRORSTATUS/HTMLSTATUS", true);


        _EMAILSTATUS_validator_ = new XmlValidator("ERRORSTATUS_1.EMAILSTATUS", "Element",

                "ERRORSTATUS/EMAILSTATUS", true);


        _validators_created = true;

    }


    /**
     * Checks this object to see if it will produce valid XML.
     */

    public boolean isValid() {


        if (!(this instanceof Validateable)) {

            return (true);

        }


        Vector errors = ((Validateable) this).getValidationErrors(true);

        if (errors == null || errors.size() < 1) {

            return (true);

        }


        return (false);

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     */

    public Vector getValidationErrors() {

        return (getValidationErrors(false));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error) {

        return (getValidationErrors(return_on_error, true));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error, boolean traverse) {


        createValidators();


        Vector errors;

        if (_unexpected_xml_errors_ != null &&

                _unexpected_xml_errors_.size() > 0) {

            errors = (Vector) _unexpected_xml_errors_.clone();

            if (return_on_error) {

                return (errors);

            }

        } else {

            errors = new Vector();

        }


        XmlValidationError e;


        if (!traverse) {

            if (errors.size() < 1) {

                return (null);

            }


            return (errors);

        }


        boolean is_valid;


        is_valid = _DOCSTATUS_validator_.isValid(_DOCSTATUS,

                errors, return_on_error, traverse);

        if (!is_valid && return_on_error) {

            return (errors);

        }


        is_valid = _HTMLSTATUS_validator_.isValid(_HTMLSTATUS,

                errors, return_on_error, traverse);

        if (!is_valid && return_on_error) {

            return (errors);

        }


        is_valid = _EMAILSTATUS_validator_.isValid(_EMAILSTATUS,

                errors, return_on_error, traverse);

        if (!is_valid && return_on_error) {

            return (errors);

        }


        if (errors.size() < 1) {

            return (null);

        }


        return (errors);

    }


    /**
     * Checks the XML to see whether it matches the
     * <p/>
     * XML contents of this class.
     */

    public static boolean matches(XmlElement xml) {


        if (xml == null) {

            return (false);

        }


        return (xml.equals($ERRORSTATUS));

    }


    /**
     * This method unmarshals an XML document instance
     * <p/>
     * into an instance of this class.
     */

    public static ERRORSTATUS_1 unmarshal(InputStream in) throws Exception {


        ERRORSTATUS_1 obj = new ERRORSTATUS_1();

        ObjectFactory.unmarshal(obj, in);

        return (obj);

    }


    /**
     * Populates this object with the values from the
     * <p/>
     * parsed XML.
     */

    public void fromXml(XmlElement xml) {


        if (xml == null) {

            return;

        }


        if (!xml.equals($ERRORSTATUS)) {

            return;

        }





        /*

         * Get the contained XmlElement, this is what we process

         */

        xml = xml.getSubElementAt(0);

        if (xml == null) {

            return;

        }


        if (xml.equals($DOCSTATUS)) {

            setDOCSTATUS(xml);

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($HTMLSTATUS)) {

            setHTMLSTATUS(xml);

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($EMAILSTATUS)) {

            setEMAILSTATUS(xml);

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml != null) {


            _unexpected_xml_errors_ =

                    XmlValidationError.addUnexpectedXmlError(this, _unexpected_xml_errors_, xml);

            xml = xml.next();

        }

    }


    /**
     * This method marshals this object into an
     * <p/>
     * XML instance document.
     */

    public void marshal(OutputStream out) {

        toXml(out);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream) {

        toXml(stream, true);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream, String indent, boolean embed_files) {


        if (stream instanceof XmlOutputStream) {

            toXml(stream, embed_files);

        } else {

            FormattedOutputStream out =

                    new FormattedOutputStream(stream);

            out.setIndentString(indent);

            toXml(out, embed_files);

        }

    }


    /**
     * Serializes this object to XML.
     */

    public void toXml(OutputStream stream, boolean embed_files) {


        XmlOutputStream out = null;

        if (stream instanceof XmlOutputStream) {

            out = (XmlOutputStream) stream;

        } else {

            out = new RawOutputStream(stream);

        }


        out.writeStartTag(getXmlTagName(), false);

        out.incrementIndent();


        Object DOCSTATUS_value = getDOCSTATUS();

        if (DOCSTATUS_value instanceof XmlObject) {

            out.write(null,

                    (XmlObject) DOCSTATUS_value,

                    embed_files);

        }


        Object HTMLSTATUS_value = getHTMLSTATUS();

        if (HTMLSTATUS_value instanceof XmlObject) {

            out.write(null,

                    (XmlObject) HTMLSTATUS_value,

                    embed_files);

        }


        Object EMAILSTATUS_value = getEMAILSTATUS();

        if (EMAILSTATUS_value instanceof XmlObject) {

            out.write(null,

                    (XmlObject) EMAILSTATUS_value,

                    embed_files);

        }


        out.decrementIndent();

        out.writeEndTag(getXmlTagName());

    }


    /**
     * Get the  birth certificate for this object.
     */

    public String birthCertificate() {

        return ("1hge137:cy11q38b:1ydef7x");

    }

}
