/*

 * DO NOT EDIT!

 *

 * This file was generated by the Breeze XML Studio Java Export Wizard.

 *

 *        Project: connectship

 *     Class Name: LABELPRINT

 *           Date: Fri Feb 22 21:58:50 PST 2002

 * Breeze Version: 2.2.1 build 114

 *

 * IMPORTANT: Please see your Breeze license for more information on

 *            where and how this generated code may be used.

 *

 */


package com.owd.core.csXml;


import com.tbf.xml.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;


/**
 * LABELPRINT class.
 */

public class LABELPRINT

        implements com.tbf.xml.XmlObject, Validateable, java.io.Serializable {
private final static Logger log =  LogManager.getLogger();


    /**
     * Constant for "PRINTERMODELSYMBOL" node name.
     */

    public static final String $PRINTERMODELSYMBOL = "PRINTERMODELSYMBOL";


    /**
     * Constant for "LABELPRINT" node name.
     */

    public static final String $LABELPRINT = "LABELPRINT";


    /**
     * Constant for "PORT" node name.
     */

    public static final String $PORT = "PORT";


    /**
     * Constant for "STOCKSYMBOL" node name.
     */

    public static final String $STOCKSYMBOL = "STOCKSYMBOL";


    protected String _PORT = null;

    protected String _STOCKSYMBOL = null;

    protected String _PRINTERMODELSYMBOL = null;


    /**
     * Storage for UNEXPECTED_XML errors.
     */

    protected Vector _unexpected_xml_errors_ = null;


    /**
     * Default no args constructor.
     */

    public LABELPRINT() {

    }


    /**
     * Creates and populates an instance from the provided parse tree.
     *
     * @param xml the parse tree
     */

    public LABELPRINT(XmlElement xml) {

        fromXml(xml);

    }


    /**
     * Get the PORT property.
     */

    public String getPORT() {

        return (_PORT);

    }


    /**
     * Set the PORT property.
     */

    public void setPORT(String newValue) {

        _PORT = newValue;

    }


    /**
     * Checks for whether PORT is set or not.
     *
     * @returns true if PORT is set, false if not
     */

    public boolean hasPORT() {

        return (_PORT != null);

    }


    /**
     * Discards PORT's value.
     */

    public void deletePORT() {

        _PORT = null;

    }


    /**
     * Get the STOCKSYMBOL property.
     */

    public String getSTOCKSYMBOL() {

        return (_STOCKSYMBOL);

    }


    /**
     * Set the STOCKSYMBOL property.
     */

    public void setSTOCKSYMBOL(String newValue) {

        _STOCKSYMBOL = newValue;

    }


    /**
     * Checks for whether STOCKSYMBOL is set or not.
     *
     * @returns true if STOCKSYMBOL is set, false if not
     */

    public boolean hasSTOCKSYMBOL() {

        return (_STOCKSYMBOL != null);

    }


    /**
     * Discards STOCKSYMBOL's value.
     */

    public void deleteSTOCKSYMBOL() {

        _STOCKSYMBOL = null;

    }


    /**
     * Get the PRINTERMODELSYMBOL property.
     */

    public String getPRINTERMODELSYMBOL() {

        return (_PRINTERMODELSYMBOL);

    }


    /**
     * Set the PRINTERMODELSYMBOL property.
     */

    public void setPRINTERMODELSYMBOL(String newValue) {

        _PRINTERMODELSYMBOL = newValue;

    }


    /**
     * Checks for whether PRINTERMODELSYMBOL is set or not.
     *
     * @returns true if PRINTERMODELSYMBOL is set, false if not
     */

    public boolean hasPRINTERMODELSYMBOL() {

        return (_PRINTERMODELSYMBOL != null);

    }


    /**
     * Discards PRINTERMODELSYMBOL's value.
     */

    public void deletePRINTERMODELSYMBOL() {

        _PRINTERMODELSYMBOL = null;

    }


    /**
     * Gets the XML tag name for this object.
     */

    public String getXmlTagName() {

        return ($LABELPRINT);

    }


    /**
     * Gets the XML tag name for this class.
     */

    public static String getClassXmlTagName() {

        return ($LABELPRINT);

    }


    /**
     * This flag is used to used to check whether
     * <p/>
     * the validators have been created.
     */

    transient protected static boolean _validators_created = false;



    /*

     * XML Validators

     */

    transient protected static XmlStringValidator

            _PORT_validator_ = null;

    transient protected static XmlStringValidator

            _STOCKSYMBOL_validator_ = null;

    transient protected static XmlStringValidator

            _PRINTERMODELSYMBOL_validator_ = null;


    /**
     * Create the validators for this class.
     */

    protected static synchronized void createValidators() {


        if (_validators_created) {

            return;

        }


        _PORT_validator_ = new XmlStringValidator("LABELPRINT.PORT", "Element",

                "LABELPRINT/PORT", -1, -1, true);


        _STOCKSYMBOL_validator_ = new XmlStringValidator("LABELPRINT.STOCKSYMBOL", "Element",

                "LABELPRINT/STOCKSYMBOL", -1, -1, true);


        _PRINTERMODELSYMBOL_validator_ = new XmlStringValidator("LABELPRINT.PRINTERMODELSYMBOL", "Element",

                "LABELPRINT/PRINTERMODELSYMBOL", -1, -1, true);


        _validators_created = true;

    }


    /**
     * Checks this object to see if it will produce valid XML.
     */

    public boolean isValid() {


        if (!(this instanceof Validateable)) {

            return (true);

        }


        Vector errors = ((Validateable) this).getValidationErrors(true);

        if (errors == null || errors.size() < 1) {

            return (true);

        }


        return (false);

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     */

    public Vector getValidationErrors() {

        return (getValidationErrors(false));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error) {

        return (getValidationErrors(return_on_error, true));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error, boolean traverse) {


        createValidators();


        Vector errors;

        if (_unexpected_xml_errors_ != null &&

                _unexpected_xml_errors_.size() > 0) {

            errors = (Vector) _unexpected_xml_errors_.clone();

            if (return_on_error) {

                return (errors);

            }

        } else {

            errors = new Vector();

        }


        XmlValidationError e;

        e = _PORT_validator_.validate(_PORT);

        if (e != null) {

            errors.addElement(e);

            if (return_on_error) {

                return (errors);

            }

        }


        e = _STOCKSYMBOL_validator_.validate(_STOCKSYMBOL);

        if (e != null) {

            errors.addElement(e);

            if (return_on_error) {

                return (errors);

            }

        }


        e = _PRINTERMODELSYMBOL_validator_.validate(_PRINTERMODELSYMBOL);

        if (e != null) {

            errors.addElement(e);

            if (return_on_error) {

                return (errors);

            }

        }


        if (errors.size() < 1) {

            return (null);

        }


        return (errors);

    }


    /**
     * Checks the XML to see whether it matches the
     * <p/>
     * XML contents of this class.
     */

    public static boolean matches(XmlElement xml) {


        if (xml == null) {

            return (false);

        }


        return (xml.equals($LABELPRINT));

    }


    /**
     * This method unmarshals an XML document instance
     * <p/>
     * into an instance of this class.
     */

    public static LABELPRINT unmarshal(InputStream in) throws Exception {


        LABELPRINT obj = new LABELPRINT();

        ObjectFactory.unmarshal(obj, in);

        return (obj);

    }


    /**
     * Populates this object with the values from the
     * <p/>
     * parsed XML.
     */

    public void fromXml(XmlElement xml) {


        if (xml == null) {

            return;

        }


        if (!xml.equals($LABELPRINT)) {

            return;

        }





        /*

         * Get the contained XmlElement, this is what we process

         */

        xml = xml.getSubElementAt(0);

        if (xml == null) {

            return;

        }


        if (xml.equals($PORT)) {

            setPORT(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($STOCKSYMBOL)) {

            setSTOCKSYMBOL(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($PRINTERMODELSYMBOL)) {

            setPRINTERMODELSYMBOL(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml != null) {


            _unexpected_xml_errors_ =

                    XmlValidationError.addUnexpectedXmlError(this, _unexpected_xml_errors_, xml);

            xml = xml.next();

        }

    }


    /**
     * This method marshals this object into an
     * <p/>
     * XML instance document.
     */

    public void marshal(OutputStream out) {

        toXml(out);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream) {

        toXml(stream, true);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream, String indent, boolean embed_files) {


        if (stream instanceof XmlOutputStream) {

            toXml(stream, embed_files);

        } else {

            FormattedOutputStream out =

                    new FormattedOutputStream(stream);

            out.setIndentString(indent);

            toXml(out, embed_files);

        }

    }


    /**
     * Serializes this object to XML.
     */

    public void toXml(OutputStream stream, boolean embed_files) {


        XmlOutputStream out = null;

        if (stream instanceof XmlOutputStream) {

            out = (XmlOutputStream) stream;

        } else {

            out = new RawOutputStream(stream);

        }


        out.writeStartTag(getXmlTagName(), false);

        out.incrementIndent();


        out.write($PORT,

                _PORT);

        out.write($STOCKSYMBOL,

                _STOCKSYMBOL);

        out.write($PRINTERMODELSYMBOL,

                _PRINTERMODELSYMBOL);


        out.decrementIndent();

        out.writeEndTag(getXmlTagName());

    }


    /**
     * Get the  birth certificate for this object.
     */

    public String birthCertificate() {

        return ("1hge137:cy11q2bi:wphz0w");

    }

}
