/*

 * DO NOT EDIT!

 *

 * This file was generated by the Breeze XML Studio Java Export Wizard.

 *

 *        Project: connectship

 *     Class Name: PACKPRINT

 *           Date: Fri Feb 22 21:58:50 PST 2002

 * Breeze Version: 2.2.1 build 114

 *

 * IMPORTANT: Please see your Breeze license for more information on

 *            where and how this generated code may be used.

 *

 */


package com.owd.core.csXml;


import com.tbf.xml.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;


/**
 * PACKPRINT class.
 */

public class PACKPRINT

        implements com.tbf.xml.XmlObject, Validateable, java.io.Serializable {
private final static Logger log =  LogManager.getLogger();


    /**
     * Constant for "PACKSTOCKSYMBOL" node name.
     */

    public static final String $PACKSTOCKSYMBOL = "PACKSTOCKSYMBOL";


    /**
     * Constant for "PACKPRINTERMODELSYMBOL" node name.
     */

    public static final String $PACKPRINTERMODELSYMBOL = "PACKPRINTERMODELSYMBOL";


    /**
     * Constant for "PACKPORT" node name.
     */

    public static final String $PACKPORT = "PACKPORT";


    /**
     * Constant for "PACKPRINT" node name.
     */

    public static final String $PACKPRINT = "PACKPRINT";


    protected String _PACKPORT = null;

    protected String _PACKSTOCKSYMBOL = null;

    protected String _PACKPRINTERMODELSYMBOL = null;


    /**
     * Storage for UNEXPECTED_XML errors.
     */

    protected Vector _unexpected_xml_errors_ = null;


    /**
     * Default no args constructor.
     */

    public PACKPRINT() {

    }


    /**
     * Creates and populates an instance from the provided parse tree.
     *
     * @param xml the parse tree
     */

    public PACKPRINT(XmlElement xml) {

        fromXml(xml);

    }


    /**
     * Get the PACKPORT property.
     */

    public String getPACKPORT() {

        return (_PACKPORT);

    }


    /**
     * Set the PACKPORT property.
     */

    public void setPACKPORT(String newValue) {

        _PACKPORT = newValue;

    }


    /**
     * Checks for whether PACKPORT is set or not.
     *
     * @returns true if PACKPORT is set, false if not
     */

    public boolean hasPACKPORT() {

        return (_PACKPORT != null);

    }


    /**
     * Discards PACKPORT's value.
     */

    public void deletePACKPORT() {

        _PACKPORT = null;

    }


    /**
     * Get the PACKSTOCKSYMBOL property.
     */

    public String getPACKSTOCKSYMBOL() {

        return (_PACKSTOCKSYMBOL);

    }


    /**
     * Set the PACKSTOCKSYMBOL property.
     */

    public void setPACKSTOCKSYMBOL(String newValue) {

        _PACKSTOCKSYMBOL = newValue;

    }


    /**
     * Checks for whether PACKSTOCKSYMBOL is set or not.
     *
     * @returns true if PACKSTOCKSYMBOL is set, false if not
     */

    public boolean hasPACKSTOCKSYMBOL() {

        return (_PACKSTOCKSYMBOL != null);

    }


    /**
     * Discards PACKSTOCKSYMBOL's value.
     */

    public void deletePACKSTOCKSYMBOL() {

        _PACKSTOCKSYMBOL = null;

    }


    /**
     * Get the PACKPRINTERMODELSYMBOL property.
     */

    public String getPACKPRINTERMODELSYMBOL() {

        return (_PACKPRINTERMODELSYMBOL);

    }


    /**
     * Set the PACKPRINTERMODELSYMBOL property.
     */

    public void setPACKPRINTERMODELSYMBOL(String newValue) {

        _PACKPRINTERMODELSYMBOL = newValue;

    }


    /**
     * Checks for whether PACKPRINTERMODELSYMBOL is set or not.
     *
     * @returns true if PACKPRINTERMODELSYMBOL is set, false if not
     */

    public boolean hasPACKPRINTERMODELSYMBOL() {

        return (_PACKPRINTERMODELSYMBOL != null);

    }


    /**
     * Discards PACKPRINTERMODELSYMBOL's value.
     */

    public void deletePACKPRINTERMODELSYMBOL() {

        _PACKPRINTERMODELSYMBOL = null;

    }


    /**
     * Gets the XML tag name for this object.
     */

    public String getXmlTagName() {

        return ($PACKPRINT);

    }


    /**
     * Gets the XML tag name for this class.
     */

    public static String getClassXmlTagName() {

        return ($PACKPRINT);

    }


    /**
     * This flag is used to used to check whether
     * <p/>
     * the validators have been created.
     */

    transient protected static boolean _validators_created = false;



    /*

     * XML Validators

     */

    transient protected static XmlStringValidator

            _PACKPORT_validator_ = null;

    transient protected static XmlStringValidator

            _PACKSTOCKSYMBOL_validator_ = null;

    transient protected static XmlStringValidator

            _PACKPRINTERMODELSYMBOL_validator_ = null;


    /**
     * Create the validators for this class.
     */

    protected static synchronized void createValidators() {


        if (_validators_created) {

            return;

        }


        _PACKPORT_validator_ = new XmlStringValidator("PACKPRINT.PACKPORT", "Element",

                "PACKPRINT/PACKPORT", -1, -1, true);


        _PACKSTOCKSYMBOL_validator_ = new XmlStringValidator("PACKPRINT.PACKSTOCKSYMBOL", "Element",

                "PACKPRINT/PACKSTOCKSYMBOL", -1, -1, true);


        _PACKPRINTERMODELSYMBOL_validator_ = new XmlStringValidator("PACKPRINT.PACKPRINTERMODELSYMBOL", "Element",

                "PACKPRINT/PACKPRINTERMODELSYMBOL", -1, -1, true);


        _validators_created = true;

    }


    /**
     * Checks this object to see if it will produce valid XML.
     */

    public boolean isValid() {


        if (!(this instanceof Validateable)) {

            return (true);

        }


        Vector errors = ((Validateable) this).getValidationErrors(true);

        if (errors == null || errors.size() < 1) {

            return (true);

        }


        return (false);

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     */

    public Vector getValidationErrors() {

        return (getValidationErrors(false));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error) {

        return (getValidationErrors(return_on_error, true));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error, boolean traverse) {


        createValidators();


        Vector errors;

        if (_unexpected_xml_errors_ != null &&

                _unexpected_xml_errors_.size() > 0) {

            errors = (Vector) _unexpected_xml_errors_.clone();

            if (return_on_error) {

                return (errors);

            }

        } else {

            errors = new Vector();

        }


        XmlValidationError e;

        e = _PACKPORT_validator_.validate(_PACKPORT);

        if (e != null) {

            errors.addElement(e);

            if (return_on_error) {

                return (errors);

            }

        }


        e = _PACKSTOCKSYMBOL_validator_.validate(_PACKSTOCKSYMBOL);

        if (e != null) {

            errors.addElement(e);

            if (return_on_error) {

                return (errors);

            }

        }


        e = _PACKPRINTERMODELSYMBOL_validator_.validate(_PACKPRINTERMODELSYMBOL);

        if (e != null) {

            errors.addElement(e);

            if (return_on_error) {

                return (errors);

            }

        }


        if (errors.size() < 1) {

            return (null);

        }


        return (errors);

    }


    /**
     * Checks the XML to see whether it matches the
     * <p/>
     * XML contents of this class.
     */

    public static boolean matches(XmlElement xml) {


        if (xml == null) {

            return (false);

        }


        return (xml.equals($PACKPRINT));

    }


    /**
     * This method unmarshals an XML document instance
     * <p/>
     * into an instance of this class.
     */

    public static PACKPRINT unmarshal(InputStream in) throws Exception {


        PACKPRINT obj = new PACKPRINT();

        ObjectFactory.unmarshal(obj, in);

        return (obj);

    }


    /**
     * Populates this object with the values from the
     * <p/>
     * parsed XML.
     */

    public void fromXml(XmlElement xml) {


        if (xml == null) {

            return;

        }


        if (!xml.equals($PACKPRINT)) {

            return;

        }





        /*

         * Get the contained XmlElement, this is what we process

         */

        xml = xml.getSubElementAt(0);

        if (xml == null) {

            return;

        }


        if (xml.equals($PACKPORT)) {

            setPACKPORT(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($PACKSTOCKSYMBOL)) {

            setPACKSTOCKSYMBOL(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($PACKPRINTERMODELSYMBOL)) {

            setPACKPRINTERMODELSYMBOL(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml != null) {


            _unexpected_xml_errors_ =

                    XmlValidationError.addUnexpectedXmlError(this, _unexpected_xml_errors_, xml);

            xml = xml.next();

        }

    }


    /**
     * This method marshals this object into an
     * <p/>
     * XML instance document.
     */

    public void marshal(OutputStream out) {

        toXml(out);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream) {

        toXml(stream, true);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream, String indent, boolean embed_files) {


        if (stream instanceof XmlOutputStream) {

            toXml(stream, embed_files);

        } else {

            FormattedOutputStream out =

                    new FormattedOutputStream(stream);

            out.setIndentString(indent);

            toXml(out, embed_files);

        }

    }


    /**
     * Serializes this object to XML.
     */

    public void toXml(OutputStream stream, boolean embed_files) {


        XmlOutputStream out = null;

        if (stream instanceof XmlOutputStream) {

            out = (XmlOutputStream) stream;

        } else {

            out = new RawOutputStream(stream);

        }


        out.writeStartTag(getXmlTagName(), false);

        out.incrementIndent();


        out.write($PACKPORT,

                _PACKPORT);

        out.write($PACKSTOCKSYMBOL,

                _PACKSTOCKSYMBOL);

        out.write($PACKPRINTERMODELSYMBOL,

                _PACKPRINTERMODELSYMBOL);


        out.decrementIndent();

        out.writeEndTag(getXmlTagName());

    }


    /**
     * Get the  birth certificate for this object.
     */

    public String birthCertificate() {

        return ("1hge137:cy11q2ok:gbel96");

    }

}
