/*

 * DO NOT EDIT!

 *

 * This file was generated by the Breeze XML Studio Java Export Wizard.

 *

 *        Project: connectship

 *     Class Name: RETURNDELIVERY

 *           Date: Fri Feb 22 21:58:50 PST 2002

 * Breeze Version: 2.2.1 build 114

 *

 * IMPORTANT: Please see your Breeze license for more information on

 *            where and how this generated code may be used.

 *

 */


package com.owd.core.csXml;


import com.tbf.xml.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;


/**
 * RETURNDELIVERY class.
 */

public class RETURNDELIVERY

        implements com.tbf.xml.XmlObject, Validateable, java.io.Serializable {
private final static Logger log =  LogManager.getLogger();


    /**
     * Constant for "RETURNDELIVERYFLAG" node name.
     */

    public static final String $RETURNDELIVERYFLAG = "RETURNDELIVERYFLAG";


    /**
     * Constant for "DIMENSION" node name.
     */

    public static final String $DIMENSION = "DIMENSION";


    /**
     * Constant for "PACKAGING" node name.
     */

    public static final String $PACKAGING = "PACKAGING";


    /**
     * Constant for "RETURNADDRESS" node name.
     */

    public static final String $RETURNADDRESS = "RETURNADDRESS";


    /**
     * Constant for "RETURNDELIVERY" node name.
     */

    public static final String $RETURNDELIVERY = "RETURNDELIVERY";


    protected String _RETURNDELIVERYFLAG = null;

    protected RETURNADDRESS _RETURNADDRESS = null;

    protected DIMENSION _DIMENSION = null;

    protected String _PACKAGING = null;


    /**
     * Storage for UNEXPECTED_XML errors.
     */

    protected Vector _unexpected_xml_errors_ = null;


    /**
     * Default no args constructor.
     */

    public RETURNDELIVERY() {

    }


    /**
     * Creates and populates an instance from the provided parse tree.
     *
     * @param xml the parse tree
     */

    public RETURNDELIVERY(XmlElement xml) {

        fromXml(xml);

    }


    /**
     * Get the RETURNDELIVERYFLAG property.
     */

    public String getRETURNDELIVERYFLAG() {

        return (_RETURNDELIVERYFLAG);

    }


    /**
     * Set the RETURNDELIVERYFLAG property.
     */

    public void setRETURNDELIVERYFLAG(String newValue) {

        _RETURNDELIVERYFLAG = newValue;

    }


    /**
     * Checks for whether RETURNDELIVERYFLAG is set or not.
     *
     * @returns true if RETURNDELIVERYFLAG is set, false if not
     */

    public boolean hasRETURNDELIVERYFLAG() {

        return (_RETURNDELIVERYFLAG != null);

    }


    /**
     * Discards RETURNDELIVERYFLAG's value.
     */

    public void deleteRETURNDELIVERYFLAG() {

        _RETURNDELIVERYFLAG = null;

    }


    /**
     * Get the RETURNADDRESS property.
     */

    public RETURNADDRESS getRETURNADDRESS() {

        return (_RETURNADDRESS);

    }


    /**
     * Set the RETURNADDRESS property.
     */

    public void setRETURNADDRESS(RETURNADDRESS obj) {

        _RETURNADDRESS = obj;

    }


    protected void setRETURNADDRESS(XmlElement xml) {


        _RETURNADDRESS =

                new RETURNADDRESS(xml);

    }


    /**
     * Checks for whether RETURNADDRESS is set or not.
     *
     * @returns true if RETURNADDRESS is set, false if not
     */

    public boolean hasRETURNADDRESS() {

        return (_RETURNADDRESS != null);

    }


    /**
     * Discards RETURNADDRESS's value.
     */

    public void deleteRETURNADDRESS() {

        _RETURNADDRESS = null;

    }


    /**
     * Get the DIMENSION property.
     */

    public DIMENSION getDIMENSION() {

        return (_DIMENSION);

    }


    /**
     * Set the DIMENSION property.
     */

    public void setDIMENSION(DIMENSION obj) {

        _DIMENSION = obj;

    }


    protected void setDIMENSION(XmlElement xml) {


        _DIMENSION =

                new DIMENSION(xml);

    }


    /**
     * Checks for whether DIMENSION is set or not.
     *
     * @returns true if DIMENSION is set, false if not
     */

    public boolean hasDIMENSION() {

        return (_DIMENSION != null);

    }


    /**
     * Discards DIMENSION's value.
     */

    public void deleteDIMENSION() {

        _DIMENSION = null;

    }


    /**
     * Get the PACKAGING property.
     */

    public String getPACKAGING() {

        return (_PACKAGING);

    }


    /**
     * Set the PACKAGING property.
     */

    public void setPACKAGING(String newValue) {

        _PACKAGING = newValue;

    }


    /**
     * Checks for whether PACKAGING is set or not.
     *
     * @returns true if PACKAGING is set, false if not
     */

    public boolean hasPACKAGING() {

        return (_PACKAGING != null);

    }


    /**
     * Discards PACKAGING's value.
     */

    public void deletePACKAGING() {

        _PACKAGING = null;

    }


    /**
     * Gets the XML tag name for this object.
     */

    public String getXmlTagName() {

        return ($RETURNDELIVERY);

    }


    /**
     * Gets the XML tag name for this class.
     */

    public static String getClassXmlTagName() {

        return ($RETURNDELIVERY);

    }


    /**
     * This flag is used to used to check whether
     * <p/>
     * the validators have been created.
     */

    transient protected static boolean _validators_created = false;



    /*

     * XML Validators

     */

    transient protected static XmlStringValidator

            _RETURNDELIVERYFLAG_validator_ = null;

    transient protected static XmlValidator

            _RETURNADDRESS_validator_ = null;

    transient protected static XmlValidator

            _DIMENSION_validator_ = null;

    transient protected static XmlStringValidator

            _PACKAGING_validator_ = null;


    /**
     * Create the validators for this class.
     */

    protected static synchronized void createValidators() {


        if (_validators_created) {

            return;

        }


        _RETURNDELIVERYFLAG_validator_ = new XmlStringValidator("RETURNDELIVERY.RETURNDELIVERYFLAG", "Element",

                "RETURNDELIVERY/RETURNDELIVERYFLAG", -1, -1, true);


        _RETURNADDRESS_validator_ = new XmlValidator("RETURNDELIVERY.RETURNADDRESS", "Element",

                "RETURNDELIVERY/RETURNADDRESS", false);


        _DIMENSION_validator_ = new XmlValidator("RETURNDELIVERY.DIMENSION", "Element",

                "RETURNDELIVERY/DIMENSION", true);


        _PACKAGING_validator_ = new XmlStringValidator("RETURNDELIVERY.PACKAGING", "Element",

                "RETURNDELIVERY/PACKAGING", -1, -1, true);


        _validators_created = true;

    }


    /**
     * Checks this object to see if it will produce valid XML.
     */

    public boolean isValid() {


        if (!(this instanceof Validateable)) {

            return (true);

        }


        Vector errors = ((Validateable) this).getValidationErrors(true);

        if (errors == null || errors.size() < 1) {

            return (true);

        }


        return (false);

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     */

    public Vector getValidationErrors() {

        return (getValidationErrors(false));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error) {

        return (getValidationErrors(return_on_error, true));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error, boolean traverse) {


        createValidators();


        Vector errors;

        if (_unexpected_xml_errors_ != null &&

                _unexpected_xml_errors_.size() > 0) {

            errors = (Vector) _unexpected_xml_errors_.clone();

            if (return_on_error) {

                return (errors);

            }

        } else {

            errors = new Vector();

        }


        XmlValidationError e;

        e = _RETURNDELIVERYFLAG_validator_.validate(_RETURNDELIVERYFLAG);

        if (e != null) {

            errors.addElement(e);

            if (return_on_error) {

                return (errors);

            }

        }


        e = _PACKAGING_validator_.validate(_PACKAGING);

        if (e != null) {

            errors.addElement(e);

            if (return_on_error) {

                return (errors);

            }

        }


        if (!traverse) {

            if (errors.size() < 1) {

                return (null);

            }


            return (errors);

        }


        boolean is_valid;


        is_valid = _RETURNADDRESS_validator_.isValid(_RETURNADDRESS,

                errors, return_on_error, traverse);

        if (!is_valid && return_on_error) {

            return (errors);

        }


        is_valid = _DIMENSION_validator_.isValid(_DIMENSION,

                errors, return_on_error, traverse);

        if (!is_valid && return_on_error) {

            return (errors);

        }


        if (errors.size() < 1) {

            return (null);

        }


        return (errors);

    }


    /**
     * Checks the XML to see whether it matches the
     * <p/>
     * XML contents of this class.
     */

    public static boolean matches(XmlElement xml) {


        if (xml == null) {

            return (false);

        }


        return (xml.equals($RETURNDELIVERY));

    }


    /**
     * This method unmarshals an XML document instance
     * <p/>
     * into an instance of this class.
     */

    public static RETURNDELIVERY unmarshal(InputStream in) throws Exception {


        RETURNDELIVERY obj = new RETURNDELIVERY();

        ObjectFactory.unmarshal(obj, in);

        return (obj);

    }


    /**
     * Populates this object with the values from the
     * <p/>
     * parsed XML.
     */

    public void fromXml(XmlElement xml) {


        if (xml == null) {

            return;

        }


        if (!xml.equals($RETURNDELIVERY)) {

            return;

        }





        /*

         * Get the contained XmlElement, this is what we process

         */

        xml = xml.getSubElementAt(0);

        if (xml == null) {

            return;

        }


        if (xml.equals($RETURNDELIVERYFLAG)) {

            setRETURNDELIVERYFLAG(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($RETURNADDRESS)) {

            setRETURNADDRESS(xml);

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($DIMENSION)) {

            setDIMENSION(xml);

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($PACKAGING)) {

            setPACKAGING(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml != null) {


            _unexpected_xml_errors_ =

                    XmlValidationError.addUnexpectedXmlError(this, _unexpected_xml_errors_, xml);

            xml = xml.next();

        }

    }


    /**
     * This method marshals this object into an
     * <p/>
     * XML instance document.
     */

    public void marshal(OutputStream out) {

        toXml(out);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream) {

        toXml(stream, true);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream, String indent, boolean embed_files) {


        if (stream instanceof XmlOutputStream) {

            toXml(stream, embed_files);

        } else {

            FormattedOutputStream out =

                    new FormattedOutputStream(stream);

            out.setIndentString(indent);

            toXml(out, embed_files);

        }

    }


    /**
     * Serializes this object to XML.
     */

    public void toXml(OutputStream stream, boolean embed_files) {


        XmlOutputStream out = null;

        if (stream instanceof XmlOutputStream) {

            out = (XmlOutputStream) stream;

        } else {

            out = new RawOutputStream(stream);

        }


        out.writeStartTag(getXmlTagName(), false);

        out.incrementIndent();


        out.write($RETURNDELIVERYFLAG,

                _RETURNDELIVERYFLAG);


        Object RETURNADDRESS_value = getRETURNADDRESS();

        if (RETURNADDRESS_value instanceof XmlObject) {

            out.write(null,

                    (XmlObject) RETURNADDRESS_value,

                    embed_files);

        }


        Object DIMENSION_value = getDIMENSION();

        if (DIMENSION_value instanceof XmlObject) {

            out.write(null,

                    (XmlObject) DIMENSION_value,

                    embed_files);

        }

        out.write($PACKAGING,

                _PACKAGING);


        out.decrementIndent();

        out.writeEndTag(getXmlTagName());

    }


    /**
     * Get the  birth certificate for this object.
     */

    public String birthCertificate() {

        return ("1hge137:cy11q29a:12x1lc3");

    }

}
