/*

 * DO NOT EDIT!

 *

 * This file was generated by the Breeze XML Studio Java Export Wizard.

 *

 *        Project: connectship

 *     Class Name: RETURN_1

 *           Date: Fri Feb 22 21:58:51 PST 2002

 * Breeze Version: 2.2.1 build 114

 *

 * IMPORTANT: Please see your Breeze license for more information on

 *            where and how this generated code may be used.

 *

 */


package com.owd.core.csXml;


import com.tbf.xml.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;


/**
 * RETURN_1 class.
 */

public class RETURN_1

        implements com.tbf.xml.XmlObject, Validateable, java.io.Serializable {
private final static Logger log =  LogManager.getLogger();


    /**
     * Constant for "RETURN" node name.
     */

    public static final String $RETURN = "RETURN";


    /**
     * Constant for "SEARCHRESULTS" node name.
     */

    public static final String $SEARCHRESULTS = "SEARCHRESULTS";


    /**
     * Constant for "ERRORDESCRIPTION" node name.
     */

    public static final String $ERRORDESCRIPTION = "ERRORDESCRIPTION";


    /**
     * Constant for "ERRORCODE" node name.
     */

    public static final String $ERRORCODE = "ERRORCODE";


    protected String _ERRORCODE = null;

    protected String _ERRORDESCRIPTION = null;

    protected SEARCHRESULTS _SEARCHRESULTS = null;


    /**
     * Storage for UNEXPECTED_XML errors.
     */

    protected Vector _unexpected_xml_errors_ = null;


    /**
     * Default no args constructor.
     */

    public RETURN_1() {

    }


    /**
     * Creates and populates an instance from the provided parse tree.
     *
     * @param xml the parse tree
     */

    public RETURN_1(XmlElement xml) {

        fromXml(xml);

    }


    /**
     * Get the ERRORCODE property.
     */

    public String getERRORCODE() {

        return (_ERRORCODE);

    }


    /**
     * Set the ERRORCODE property.
     */

    public void setERRORCODE(String newValue) {

        _ERRORCODE = newValue;

    }


    /**
     * Checks for whether ERRORCODE is set or not.
     *
     * @returns true if ERRORCODE is set, false if not
     */

    public boolean hasERRORCODE() {

        return (_ERRORCODE != null);

    }


    /**
     * Discards ERRORCODE's value.
     */

    public void deleteERRORCODE() {

        _ERRORCODE = null;

    }


    /**
     * Get the ERRORDESCRIPTION property.
     */

    public String getERRORDESCRIPTION() {

        return (_ERRORDESCRIPTION);

    }


    /**
     * Set the ERRORDESCRIPTION property.
     */

    public void setERRORDESCRIPTION(String newValue) {

        _ERRORDESCRIPTION = newValue;

    }


    /**
     * Checks for whether ERRORDESCRIPTION is set or not.
     *
     * @returns true if ERRORDESCRIPTION is set, false if not
     */

    public boolean hasERRORDESCRIPTION() {

        return (_ERRORDESCRIPTION != null);

    }


    /**
     * Discards ERRORDESCRIPTION's value.
     */

    public void deleteERRORDESCRIPTION() {

        _ERRORDESCRIPTION = null;

    }


    /**
     * Get the SEARCHRESULTS property.
     */

    public SEARCHRESULTS getSEARCHRESULTS() {

        return (_SEARCHRESULTS);

    }


    /**
     * Set the SEARCHRESULTS property.
     */

    public void setSEARCHRESULTS(SEARCHRESULTS obj) {

        _SEARCHRESULTS = obj;

    }


    protected void setSEARCHRESULTS(XmlElement xml) {


        _SEARCHRESULTS =

                new SEARCHRESULTS(xml);

    }


    /**
     * Checks for whether SEARCHRESULTS is set or not.
     *
     * @returns true if SEARCHRESULTS is set, false if not
     */

    public boolean hasSEARCHRESULTS() {

        return (_SEARCHRESULTS != null);

    }


    /**
     * Discards SEARCHRESULTS's value.
     */

    public void deleteSEARCHRESULTS() {

        _SEARCHRESULTS = null;

    }


    /**
     * Gets the XML tag name for this object.
     */

    public String getXmlTagName() {

        return ($RETURN);

    }


    /**
     * Gets the XML tag name for this class.
     */

    public static String getClassXmlTagName() {

        return ($RETURN);

    }


    /**
     * This flag is used to used to check whether
     * <p/>
     * the validators have been created.
     */

    transient protected static boolean _validators_created = false;



    /*

     * XML Validators

     */

    transient protected static XmlStringValidator

            _ERRORCODE_validator_ = null;

    transient protected static XmlStringValidator

            _ERRORDESCRIPTION_validator_ = null;

    transient protected static XmlValidator

            _SEARCHRESULTS_validator_ = null;


    /**
     * Create the validators for this class.
     */

    protected static synchronized void createValidators() {


        if (_validators_created) {

            return;

        }


        _ERRORCODE_validator_ = new XmlStringValidator("RETURN_1.ERRORCODE", "Element",

                "RETURN/ERRORCODE", -1, -1, true);


        _ERRORDESCRIPTION_validator_ = new XmlStringValidator("RETURN_1.ERRORDESCRIPTION", "Element",

                "RETURN/ERRORDESCRIPTION", -1, -1, true);


        _SEARCHRESULTS_validator_ = new XmlValidator("RETURN_1.SEARCHRESULTS", "Element",

                "RETURN/SEARCHRESULTS", false);


        _validators_created = true;

    }


    /**
     * Checks this object to see if it will produce valid XML.
     */

    public boolean isValid() {


        if (!(this instanceof Validateable)) {

            return (true);

        }


        Vector errors = ((Validateable) this).getValidationErrors(true);

        if (errors == null || errors.size() < 1) {

            return (true);

        }


        return (false);

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     */

    public Vector getValidationErrors() {

        return (getValidationErrors(false));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error) {

        return (getValidationErrors(return_on_error, true));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error, boolean traverse) {


        createValidators();


        Vector errors;

        if (_unexpected_xml_errors_ != null &&

                _unexpected_xml_errors_.size() > 0) {

            errors = (Vector) _unexpected_xml_errors_.clone();

            if (return_on_error) {

                return (errors);

            }

        } else {

            errors = new Vector();

        }


        XmlValidationError e;

        e = _ERRORCODE_validator_.validate(_ERRORCODE);

        if (e != null) {

            errors.addElement(e);

            if (return_on_error) {

                return (errors);

            }

        }


        e = _ERRORDESCRIPTION_validator_.validate(_ERRORDESCRIPTION);

        if (e != null) {

            errors.addElement(e);

            if (return_on_error) {

                return (errors);

            }

        }


        if (!traverse) {

            if (errors.size() < 1) {

                return (null);

            }


            return (errors);

        }


        boolean is_valid;


        is_valid = _SEARCHRESULTS_validator_.isValid(_SEARCHRESULTS,

                errors, return_on_error, traverse);

        if (!is_valid && return_on_error) {

            return (errors);

        }


        if (errors.size() < 1) {

            return (null);

        }


        return (errors);

    }


    /**
     * Checks the XML to see whether it matches the
     * <p/>
     * XML contents of this class.
     */

    public static boolean matches(XmlElement xml) {


        if (xml == null) {

            return (false);

        }


        return (xml.equals($RETURN));

    }


    /**
     * This method unmarshals an XML document instance
     * <p/>
     * into an instance of this class.
     */

    public static RETURN_1 unmarshal(InputStream in) throws Exception {


        RETURN_1 obj = new RETURN_1();

        ObjectFactory.unmarshal(obj, in);

        return (obj);

    }


    /**
     * Populates this object with the values from the
     * <p/>
     * parsed XML.
     */

    public void fromXml(XmlElement xml) {


        if (xml == null) {

            return;

        }


        if (!xml.equals($RETURN)) {

            return;

        }





        /*

         * Get the contained XmlElement, this is what we process

         */

        xml = xml.getSubElementAt(0);

        if (xml == null) {

            return;

        }


        if (xml.equals($ERRORCODE)) {

            setERRORCODE(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($ERRORDESCRIPTION)) {

            setERRORDESCRIPTION(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($SEARCHRESULTS)) {

            setSEARCHRESULTS(xml);

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml != null) {


            _unexpected_xml_errors_ =

                    XmlValidationError.addUnexpectedXmlError(this, _unexpected_xml_errors_, xml);

            xml = xml.next();

        }

    }


    /**
     * This method marshals this object into an
     * <p/>
     * XML instance document.
     */

    public void marshal(OutputStream out) {

        toXml(out);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream) {

        toXml(stream, true);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream, String indent, boolean embed_files) {


        if (stream instanceof XmlOutputStream) {

            toXml(stream, embed_files);

        } else {

            FormattedOutputStream out =

                    new FormattedOutputStream(stream);

            out.setIndentString(indent);

            toXml(out, embed_files);

        }

    }


    /**
     * Serializes this object to XML.
     */

    public void toXml(OutputStream stream, boolean embed_files) {


        XmlOutputStream out = null;

        if (stream instanceof XmlOutputStream) {

            out = (XmlOutputStream) stream;

        } else {

            out = new RawOutputStream(stream);

        }


        out.writeStartTag(getXmlTagName(), false);

        out.incrementIndent();


        out.write($ERRORCODE,

                _ERRORCODE);

        out.write($ERRORDESCRIPTION,

                _ERRORDESCRIPTION);


        Object SEARCHRESULTS_value = getSEARCHRESULTS();

        if (SEARCHRESULTS_value instanceof XmlObject) {

            out.write(null,

                    (XmlObject) SEARCHRESULTS_value,

                    embed_files);

        }


        out.decrementIndent();

        out.writeEndTag(getXmlTagName());

    }


    /**
     * Get the  birth certificate for this object.
     */

    public String birthCertificate() {

        return ("1hge137:cy11q2vj:p5xve0");

    }

}
