/*

 * DO NOT EDIT!

 *

 * This file was generated by the Breeze XML Studio Java Export Wizard.

 *

 *        Project: connectship

 *     Class Name: SEARCHFILTERS

 *           Date: Fri Feb 22 21:58:51 PST 2002

 * Breeze Version: 2.2.1 build 114

 *

 * IMPORTANT: Please see your Breeze license for more information on

 *            where and how this generated code may be used.

 *

 */


package com.owd.core.csXml;


import com.tbf.xml.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;


/**
 * SEARCHFILTERS class.
 */

public class SEARCHFILTERS

        implements com.tbf.xml.XmlObject, Validateable, java.io.Serializable {
private final static Logger log =  LogManager.getLogger();


    /**
     * Constant for "SUBCATEGORY" node name.
     */

    public static final String $SUBCATEGORY = "SUBCATEGORY";


    /**
     * Constant for "SHIPDATE" node name.
     */

    public static final String $SHIPDATE = "SHIPDATE";


    /**
     * Constant for "HAZMAT_ID" node name.
     */

    public static final String $HAZMAT_ID = "HAZMAT_ID";


    /**
     * Constant for "ZONE" node name.
     */

    public static final String $ZONE = "ZONE";


    /**
     * Constant for "MSN" node name.
     */

    public static final String $MSN = "MSN";


    /**
     * Constant for "SHIPPER" node name.
     */

    public static final String $SHIPPER = "SHIPPER";


    /**
     * Constant for "THIRD_PARTY_BILLING_ACCOUNT" node name.
     */

    public static final String $THIRD_PARTY_BILLING_ACCOUNT = "THIRD_PARTY_BILLING_ACCOUNT";


    /**
     * Constant for "CALLTAG_NUMBER" node name.
     */

    public static final String $CALLTAG_NUMBER = "CALLTAG_NUMBER";


    /**
     * Constant for "CONSIGNEE_REFERENCE" node name.
     */

    public static final String $CONSIGNEE_REFERENCE = "CONSIGNEE_REFERENCE";


    /**
     * Constant for "SEARCHFILTERS" node name.
     */

    public static final String $SEARCHFILTERS = "SEARCHFILTERS";


    /**
     * Constant for "HAZMAT_DESCRIPTION" node name.
     */

    public static final String $HAZMAT_DESCRIPTION = "HAZMAT_DESCRIPTION";


    /**
     * Constant for "BUNDLE_ID" node name.
     */

    public static final String $BUNDLE_ID = "BUNDLE_ID";


    /**
     * Constant for "DESCRIPTION" node name.
     */

    public static final String $DESCRIPTION = "DESCRIPTION";


    /**
     * Constant for "CONSIGNEE_CODE" node name.
     */

    public static final String $CONSIGNEE_CODE = "CONSIGNEE_CODE";


    /**
     * Constant for "BAR_CODE" node name.
     */

    public static final String $BAR_CODE = "BAR_CODE";


    /**
     * Constant for "ROUTING_CODE" node name.
     */

    public static final String $ROUTING_CODE = "ROUTING_CODE";


    /**
     * Constant for "TRACKING_NUMBER" node name.
     */

    public static final String $TRACKING_NUMBER = "TRACKING_NUMBER";


    /**
     * Constant for "SHIPPER_REFERENCE" node name.
     */

    public static final String $SHIPPER_REFERENCE = "SHIPPER_REFERENCE";


    /**
     * Constant for "CONSIGNEE_ACCOUNT" node name.
     */

    public static final String $CONSIGNEE_ACCOUNT = "CONSIGNEE_ACCOUNT";


    /**
     * Constant for "COD_NUMBER" node name.
     */

    public static final String $COD_NUMBER = "COD_NUMBER";


    /**
     * Constant for "PACKAGE_LIST_ID" node name.
     */

    public static final String $PACKAGE_LIST_ID = "PACKAGE_LIST_ID";


    /**
     * Constant for "HAZMAT_CLASS" node name.
     */

    public static final String $HAZMAT_CLASS = "HAZMAT_CLASS";


    protected String _BARCODE = null;

    protected String _BUNDLEID = null;

    protected String _CALLTAGNUMBER = null;

    protected String _CODNUMBER = null;

    protected String _CONSIGNEEACCOUNT = null;

    protected String _CONSIGNEECODE = null;

    protected String _CONSIGNEEREFERENCE = null;

    protected String _DESCRIPTION = null;

    protected String _HAZMATCLASS = null;

    protected String _HAZMATDESCRIPTION = null;

    protected String _HAZMATID = null;

    protected String _MSN = null;

    protected String _PACKAGELISTID = null;

    protected String _ROUTINGCODE = null;

    protected String _SHIPDATE = null;

    protected String _SHIPPER = null;

    protected String _SHIPPERREFERENCE = null;

    protected String _SUBCATEGORY = null;

    protected String _THIRDPARTYBILLINGACCOUNT = null;

    protected String _TRACKINGNUMBER = null;

    protected String _ZONE = null;


    /**
     * Storage for UNEXPECTED_XML errors.
     */

    protected Vector _unexpected_xml_errors_ = null;


    /**
     * Default no args constructor.
     */

    public SEARCHFILTERS() {

    }


    /**
     * Creates and populates an instance from the provided parse tree.
     *
     * @param xml the parse tree
     */

    public SEARCHFILTERS(XmlElement xml) {

        fromXml(xml);

    }


    /**
     * Get the BARCODE property.
     */

    public String getBARCODE() {

        return (_BARCODE);

    }


    /**
     * Set the BARCODE property.
     */

    public void setBARCODE(String newValue) {

        _BARCODE = newValue;

    }


    /**
     * Checks for whether BARCODE is set or not.
     *
     * @returns true if BARCODE is set, false if not
     */

    public boolean hasBARCODE() {

        return (_BARCODE != null);

    }


    /**
     * Discards BARCODE's value.
     */

    public void deleteBARCODE() {

        _BARCODE = null;

    }


    /**
     * Get the BUNDLEID property.
     */

    public String getBUNDLEID() {

        return (_BUNDLEID);

    }


    /**
     * Set the BUNDLEID property.
     */

    public void setBUNDLEID(String newValue) {

        _BUNDLEID = newValue;

    }


    /**
     * Checks for whether BUNDLEID is set or not.
     *
     * @returns true if BUNDLEID is set, false if not
     */

    public boolean hasBUNDLEID() {

        return (_BUNDLEID != null);

    }


    /**
     * Discards BUNDLEID's value.
     */

    public void deleteBUNDLEID() {

        _BUNDLEID = null;

    }


    /**
     * Get the CALLTAGNUMBER property.
     */

    public String getCALLTAGNUMBER() {

        return (_CALLTAGNUMBER);

    }


    /**
     * Set the CALLTAGNUMBER property.
     */

    public void setCALLTAGNUMBER(String newValue) {

        _CALLTAGNUMBER = newValue;

    }


    /**
     * Checks for whether CALLTAGNUMBER is set or not.
     *
     * @returns true if CALLTAGNUMBER is set, false if not
     */

    public boolean hasCALLTAGNUMBER() {

        return (_CALLTAGNUMBER != null);

    }


    /**
     * Discards CALLTAGNUMBER's value.
     */

    public void deleteCALLTAGNUMBER() {

        _CALLTAGNUMBER = null;

    }


    /**
     * Get the CODNUMBER property.
     */

    public String getCODNUMBER() {

        return (_CODNUMBER);

    }


    /**
     * Set the CODNUMBER property.
     */

    public void setCODNUMBER(String newValue) {

        _CODNUMBER = newValue;

    }


    /**
     * Checks for whether CODNUMBER is set or not.
     *
     * @returns true if CODNUMBER is set, false if not
     */

    public boolean hasCODNUMBER() {

        return (_CODNUMBER != null);

    }


    /**
     * Discards CODNUMBER's value.
     */

    public void deleteCODNUMBER() {

        _CODNUMBER = null;

    }


    /**
     * Get the CONSIGNEEACCOUNT property.
     */

    public String getCONSIGNEEACCOUNT() {

        return (_CONSIGNEEACCOUNT);

    }


    /**
     * Set the CONSIGNEEACCOUNT property.
     */

    public void setCONSIGNEEACCOUNT(String newValue) {

        _CONSIGNEEACCOUNT = newValue;

    }


    /**
     * Checks for whether CONSIGNEEACCOUNT is set or not.
     *
     * @returns true if CONSIGNEEACCOUNT is set, false if not
     */

    public boolean hasCONSIGNEEACCOUNT() {

        return (_CONSIGNEEACCOUNT != null);

    }


    /**
     * Discards CONSIGNEEACCOUNT's value.
     */

    public void deleteCONSIGNEEACCOUNT() {

        _CONSIGNEEACCOUNT = null;

    }


    /**
     * Get the CONSIGNEECODE property.
     */

    public String getCONSIGNEECODE() {

        return (_CONSIGNEECODE);

    }


    /**
     * Set the CONSIGNEECODE property.
     */

    public void setCONSIGNEECODE(String newValue) {

        _CONSIGNEECODE = newValue;

    }


    /**
     * Checks for whether CONSIGNEECODE is set or not.
     *
     * @returns true if CONSIGNEECODE is set, false if not
     */

    public boolean hasCONSIGNEECODE() {

        return (_CONSIGNEECODE != null);

    }


    /**
     * Discards CONSIGNEECODE's value.
     */

    public void deleteCONSIGNEECODE() {

        _CONSIGNEECODE = null;

    }


    /**
     * Get the CONSIGNEEREFERENCE property.
     */

    public String getCONSIGNEEREFERENCE() {

        return (_CONSIGNEEREFERENCE);

    }


    /**
     * Set the CONSIGNEEREFERENCE property.
     */

    public void setCONSIGNEEREFERENCE(String newValue) {

        _CONSIGNEEREFERENCE = newValue;

    }


    /**
     * Checks for whether CONSIGNEEREFERENCE is set or not.
     *
     * @returns true if CONSIGNEEREFERENCE is set, false if not
     */

    public boolean hasCONSIGNEEREFERENCE() {

        return (_CONSIGNEEREFERENCE != null);

    }


    /**
     * Discards CONSIGNEEREFERENCE's value.
     */

    public void deleteCONSIGNEEREFERENCE() {

        _CONSIGNEEREFERENCE = null;

    }


    /**
     * Get the DESCRIPTION property.
     */

    public String getDESCRIPTION() {

        return (_DESCRIPTION);

    }


    /**
     * Set the DESCRIPTION property.
     */

    public void setDESCRIPTION(String newValue) {

        _DESCRIPTION = newValue;

    }


    /**
     * Checks for whether DESCRIPTION is set or not.
     *
     * @returns true if DESCRIPTION is set, false if not
     */

    public boolean hasDESCRIPTION() {

        return (_DESCRIPTION != null);

    }


    /**
     * Discards DESCRIPTION's value.
     */

    public void deleteDESCRIPTION() {

        _DESCRIPTION = null;

    }


    /**
     * Get the HAZMATCLASS property.
     */

    public String getHAZMATCLASS() {

        return (_HAZMATCLASS);

    }


    /**
     * Set the HAZMATCLASS property.
     */

    public void setHAZMATCLASS(String newValue) {

        _HAZMATCLASS = newValue;

    }


    /**
     * Checks for whether HAZMATCLASS is set or not.
     *
     * @returns true if HAZMATCLASS is set, false if not
     */

    public boolean hasHAZMATCLASS() {

        return (_HAZMATCLASS != null);

    }


    /**
     * Discards HAZMATCLASS's value.
     */

    public void deleteHAZMATCLASS() {

        _HAZMATCLASS = null;

    }


    /**
     * Get the HAZMATDESCRIPTION property.
     */

    public String getHAZMATDESCRIPTION() {

        return (_HAZMATDESCRIPTION);

    }


    /**
     * Set the HAZMATDESCRIPTION property.
     */

    public void setHAZMATDESCRIPTION(String newValue) {

        _HAZMATDESCRIPTION = newValue;

    }


    /**
     * Checks for whether HAZMATDESCRIPTION is set or not.
     *
     * @returns true if HAZMATDESCRIPTION is set, false if not
     */

    public boolean hasHAZMATDESCRIPTION() {

        return (_HAZMATDESCRIPTION != null);

    }


    /**
     * Discards HAZMATDESCRIPTION's value.
     */

    public void deleteHAZMATDESCRIPTION() {

        _HAZMATDESCRIPTION = null;

    }


    /**
     * Get the HAZMATID property.
     */

    public String getHAZMATID() {

        return (_HAZMATID);

    }


    /**
     * Set the HAZMATID property.
     */

    public void setHAZMATID(String newValue) {

        _HAZMATID = newValue;

    }


    /**
     * Checks for whether HAZMATID is set or not.
     *
     * @returns true if HAZMATID is set, false if not
     */

    public boolean hasHAZMATID() {

        return (_HAZMATID != null);

    }


    /**
     * Discards HAZMATID's value.
     */

    public void deleteHAZMATID() {

        _HAZMATID = null;

    }


    /**
     * Get the MSN property.
     */

    public String getMSN() {

        return (_MSN);

    }


    /**
     * Set the MSN property.
     */

    public void setMSN(String newValue) {

        _MSN = newValue;

    }


    /**
     * Checks for whether MSN is set or not.
     *
     * @returns true if MSN is set, false if not
     */

    public boolean hasMSN() {

        return (_MSN != null);

    }


    /**
     * Discards MSN's value.
     */

    public void deleteMSN() {

        _MSN = null;

    }


    /**
     * Get the PACKAGELISTID property.
     */

    public String getPACKAGELISTID() {

        return (_PACKAGELISTID);

    }


    /**
     * Set the PACKAGELISTID property.
     */

    public void setPACKAGELISTID(String newValue) {

        _PACKAGELISTID = newValue;

    }


    /**
     * Checks for whether PACKAGELISTID is set or not.
     *
     * @returns true if PACKAGELISTID is set, false if not
     */

    public boolean hasPACKAGELISTID() {

        return (_PACKAGELISTID != null);

    }


    /**
     * Discards PACKAGELISTID's value.
     */

    public void deletePACKAGELISTID() {

        _PACKAGELISTID = null;

    }


    /**
     * Get the ROUTINGCODE property.
     */

    public String getROUTINGCODE() {

        return (_ROUTINGCODE);

    }


    /**
     * Set the ROUTINGCODE property.
     */

    public void setROUTINGCODE(String newValue) {

        _ROUTINGCODE = newValue;

    }


    /**
     * Checks for whether ROUTINGCODE is set or not.
     *
     * @returns true if ROUTINGCODE is set, false if not
     */

    public boolean hasROUTINGCODE() {

        return (_ROUTINGCODE != null);

    }


    /**
     * Discards ROUTINGCODE's value.
     */

    public void deleteROUTINGCODE() {

        _ROUTINGCODE = null;

    }


    /**
     * Get the SHIPDATE property.
     */

    public String getSHIPDATE() {

        return (_SHIPDATE);

    }


    /**
     * Set the SHIPDATE property.
     */

    public void setSHIPDATE(String newValue) {

        _SHIPDATE = newValue;

    }


    /**
     * Checks for whether SHIPDATE is set or not.
     *
     * @returns true if SHIPDATE is set, false if not
     */

    public boolean hasSHIPDATE() {

        return (_SHIPDATE != null);

    }


    /**
     * Discards SHIPDATE's value.
     */

    public void deleteSHIPDATE() {

        _SHIPDATE = null;

    }


    /**
     * Get the SHIPPER property.
     */

    public String getSHIPPER() {

        return (_SHIPPER);

    }


    /**
     * Set the SHIPPER property.
     */

    public void setSHIPPER(String newValue) {

        _SHIPPER = newValue;

    }


    /**
     * Checks for whether SHIPPER is set or not.
     *
     * @returns true if SHIPPER is set, false if not
     */

    public boolean hasSHIPPER() {

        return (_SHIPPER != null);

    }


    /**
     * Discards SHIPPER's value.
     */

    public void deleteSHIPPER() {

        _SHIPPER = null;

    }


    /**
     * Get the SHIPPERREFERENCE property.
     */

    public String getSHIPPERREFERENCE() {

        return (_SHIPPERREFERENCE);

    }


    /**
     * Set the SHIPPERREFERENCE property.
     */

    public void setSHIPPERREFERENCE(String newValue) {

        _SHIPPERREFERENCE = newValue;

    }


    /**
     * Checks for whether SHIPPERREFERENCE is set or not.
     *
     * @returns true if SHIPPERREFERENCE is set, false if not
     */

    public boolean hasSHIPPERREFERENCE() {

        return (_SHIPPERREFERENCE != null);

    }


    /**
     * Discards SHIPPERREFERENCE's value.
     */

    public void deleteSHIPPERREFERENCE() {

        _SHIPPERREFERENCE = null;

    }


    /**
     * Get the SUBCATEGORY property.
     */

    public String getSUBCATEGORY() {

        return (_SUBCATEGORY);

    }


    /**
     * Set the SUBCATEGORY property.
     */

    public void setSUBCATEGORY(String newValue) {

        _SUBCATEGORY = newValue;

    }


    /**
     * Checks for whether SUBCATEGORY is set or not.
     *
     * @returns true if SUBCATEGORY is set, false if not
     */

    public boolean hasSUBCATEGORY() {

        return (_SUBCATEGORY != null);

    }


    /**
     * Discards SUBCATEGORY's value.
     */

    public void deleteSUBCATEGORY() {

        _SUBCATEGORY = null;

    }


    /**
     * Get the THIRDPARTYBILLINGACCOUNT property.
     */

    public String getTHIRDPARTYBILLINGACCOUNT() {

        return (_THIRDPARTYBILLINGACCOUNT);

    }


    /**
     * Set the THIRDPARTYBILLINGACCOUNT property.
     */

    public void setTHIRDPARTYBILLINGACCOUNT(String newValue) {

        _THIRDPARTYBILLINGACCOUNT = newValue;

    }


    /**
     * Checks for whether THIRDPARTYBILLINGACCOUNT is set or not.
     *
     * @returns true if THIRDPARTYBILLINGACCOUNT is set, false if not
     */

    public boolean hasTHIRDPARTYBILLINGACCOUNT() {

        return (_THIRDPARTYBILLINGACCOUNT != null);

    }


    /**
     * Discards THIRDPARTYBILLINGACCOUNT's value.
     */

    public void deleteTHIRDPARTYBILLINGACCOUNT() {

        _THIRDPARTYBILLINGACCOUNT = null;

    }


    /**
     * Get the TRACKINGNUMBER property.
     */

    public String getTRACKINGNUMBER() {

        return (_TRACKINGNUMBER);

    }


    /**
     * Set the TRACKINGNUMBER property.
     */

    public void setTRACKINGNUMBER(String newValue) {

        _TRACKINGNUMBER = newValue;

    }


    /**
     * Checks for whether TRACKINGNUMBER is set or not.
     *
     * @returns true if TRACKINGNUMBER is set, false if not
     */

    public boolean hasTRACKINGNUMBER() {

        return (_TRACKINGNUMBER != null);

    }


    /**
     * Discards TRACKINGNUMBER's value.
     */

    public void deleteTRACKINGNUMBER() {

        _TRACKINGNUMBER = null;

    }


    /**
     * Get the ZONE property.
     */

    public String getZONE() {

        return (_ZONE);

    }


    /**
     * Set the ZONE property.
     */

    public void setZONE(String newValue) {

        _ZONE = newValue;

    }


    /**
     * Checks for whether ZONE is set or not.
     *
     * @returns true if ZONE is set, false if not
     */

    public boolean hasZONE() {

        return (_ZONE != null);

    }


    /**
     * Discards ZONE's value.
     */

    public void deleteZONE() {

        _ZONE = null;

    }


    /**
     * Gets the XML tag name for this object.
     */

    public String getXmlTagName() {

        return ($SEARCHFILTERS);

    }


    /**
     * Gets the XML tag name for this class.
     */

    public static String getClassXmlTagName() {

        return ($SEARCHFILTERS);

    }


    /**
     * This flag is used to used to check whether
     * <p/>
     * the validators have been created.
     */

    transient protected static boolean _validators_created = false;



    /*

     * XML Validators

     */

    transient protected static XmlStringValidator

            _SHIPDATE_validator_ = null;


    /**
     * Create the validators for this class.
     */

    protected static synchronized void createValidators() {


        if (_validators_created) {

            return;

        }


        _SHIPDATE_validator_ = new XmlStringValidator("SEARCHFILTERS.SHIPDATE", "Element",

                "SEARCHFILTERS/SHIPDATE", -1, -1, true);


        _validators_created = true;

    }


    /**
     * Checks this object to see if it will produce valid XML.
     */

    public boolean isValid() {


        if (!(this instanceof Validateable)) {

            return (true);

        }


        Vector errors = ((Validateable) this).getValidationErrors(true);

        if (errors == null || errors.size() < 1) {

            return (true);

        }


        return (false);

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     */

    public Vector getValidationErrors() {

        return (getValidationErrors(false));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error) {

        return (getValidationErrors(return_on_error, true));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error, boolean traverse) {


        createValidators();


        Vector errors;

        if (_unexpected_xml_errors_ != null &&

                _unexpected_xml_errors_.size() > 0) {

            errors = (Vector) _unexpected_xml_errors_.clone();

            if (return_on_error) {

                return (errors);

            }

        } else {

            errors = new Vector();

        }


        XmlValidationError e;

        e = _SHIPDATE_validator_.validate(_SHIPDATE);

        if (e != null) {

            errors.addElement(e);

            if (return_on_error) {

                return (errors);

            }

        }


        if (errors.size() < 1) {

            return (null);

        }


        return (errors);

    }


    /**
     * Checks the XML to see whether it matches the
     * <p/>
     * XML contents of this class.
     */

    public static boolean matches(XmlElement xml) {


        if (xml == null) {

            return (false);

        }


        return (xml.equals($SEARCHFILTERS));

    }


    /**
     * This method unmarshals an XML document instance
     * <p/>
     * into an instance of this class.
     */

    public static SEARCHFILTERS unmarshal(InputStream in) throws Exception {


        SEARCHFILTERS obj = new SEARCHFILTERS();

        ObjectFactory.unmarshal(obj, in);

        return (obj);

    }


    /**
     * Populates this object with the values from the
     * <p/>
     * parsed XML.
     */

    public void fromXml(XmlElement xml) {


        if (xml == null) {

            return;

        }


        if (!xml.equals($SEARCHFILTERS)) {

            return;

        }





        /*

         * Get the contained XmlElement, this is what we process

         */

        xml = xml.getSubElementAt(0);

        if (xml == null) {

            return;

        }


        if (xml.equals($BAR_CODE)) {

            setBARCODE(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($BUNDLE_ID)) {

            setBUNDLEID(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($CALLTAG_NUMBER)) {

            setCALLTAGNUMBER(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($COD_NUMBER)) {

            setCODNUMBER(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($CONSIGNEE_ACCOUNT)) {

            setCONSIGNEEACCOUNT(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($CONSIGNEE_CODE)) {

            setCONSIGNEECODE(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($CONSIGNEE_REFERENCE)) {

            setCONSIGNEEREFERENCE(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($DESCRIPTION)) {

            setDESCRIPTION(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($HAZMAT_CLASS)) {

            setHAZMATCLASS(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($HAZMAT_DESCRIPTION)) {

            setHAZMATDESCRIPTION(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($HAZMAT_ID)) {

            setHAZMATID(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($MSN)) {

            setMSN(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($PACKAGE_LIST_ID)) {

            setPACKAGELISTID(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($ROUTING_CODE)) {

            setROUTINGCODE(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($SHIPDATE)) {

            setSHIPDATE(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($SHIPPER)) {

            setSHIPPER(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($SHIPPER_REFERENCE)) {

            setSHIPPERREFERENCE(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($SUBCATEGORY)) {

            setSUBCATEGORY(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($THIRD_PARTY_BILLING_ACCOUNT)) {

            setTHIRDPARTYBILLINGACCOUNT(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($TRACKING_NUMBER)) {

            setTRACKINGNUMBER(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($ZONE)) {

            setZONE(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml != null) {


            _unexpected_xml_errors_ =

                    XmlValidationError.addUnexpectedXmlError(this, _unexpected_xml_errors_, xml);

            xml = xml.next();

        }

    }


    /**
     * This method marshals this object into an
     * <p/>
     * XML instance document.
     */

    public void marshal(OutputStream out) {

        toXml(out);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream) {

        toXml(stream, true);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream, String indent, boolean embed_files) {


        if (stream instanceof XmlOutputStream) {

            toXml(stream, embed_files);

        } else {

            FormattedOutputStream out =

                    new FormattedOutputStream(stream);

            out.setIndentString(indent);

            toXml(out, embed_files);

        }

    }


    /**
     * Serializes this object to XML.
     */

    public void toXml(OutputStream stream, boolean embed_files) {


        XmlOutputStream out = null;

        if (stream instanceof XmlOutputStream) {

            out = (XmlOutputStream) stream;

        } else {

            out = new RawOutputStream(stream);

        }


        out.writeStartTag(getXmlTagName(), false);

        out.incrementIndent();


        out.write($BAR_CODE,

                _BARCODE);

        out.write($BUNDLE_ID,

                _BUNDLEID);

        out.write($CALLTAG_NUMBER,

                _CALLTAGNUMBER);

        out.write($COD_NUMBER,

                _CODNUMBER);

        out.write($CONSIGNEE_ACCOUNT,

                _CONSIGNEEACCOUNT);

        out.write($CONSIGNEE_CODE,

                _CONSIGNEECODE);

        out.write($CONSIGNEE_REFERENCE,

                _CONSIGNEEREFERENCE);

        out.write($DESCRIPTION,

                _DESCRIPTION);

        out.write($HAZMAT_CLASS,

                _HAZMATCLASS);

        out.write($HAZMAT_DESCRIPTION,

                _HAZMATDESCRIPTION);

        out.write($HAZMAT_ID,

                _HAZMATID);

        out.write($MSN,

                _MSN);

        out.write($PACKAGE_LIST_ID,

                _PACKAGELISTID);

        out.write($ROUTING_CODE,

                _ROUTINGCODE);

        out.write($SHIPDATE,

                _SHIPDATE);

        out.write($SHIPPER,

                _SHIPPER);

        out.write($SHIPPER_REFERENCE,

                _SHIPPERREFERENCE);

        out.write($SUBCATEGORY,

                _SUBCATEGORY);

        out.write($THIRD_PARTY_BILLING_ACCOUNT,

                _THIRDPARTYBILLINGACCOUNT);

        out.write($TRACKING_NUMBER,

                _TRACKINGNUMBER);

        out.write($ZONE,

                _ZONE);


        out.decrementIndent();

        out.writeEndTag(getXmlTagName());

    }


    /**
     * Get the  birth certificate for this object.
     */

    public String birthCertificate() {

        return ("1hge137:cy11q2up:og5wel");

    }

}
