/*

 * DO NOT EDIT!

 *

 * This file was generated by the Breeze XML Studio Java Export Wizard.

 *

 *        Project: connectship

 *     Class Name: SHIPMENTREQUEST

 *           Date: Fri Feb 22 21:58:51 PST 2002

 * Breeze Version: 2.2.1 build 114

 *

 * IMPORTANT: Please see your Breeze license for more information on

 *            where and how this generated code may be used.

 *

 */


package com.owd.core.csXml;


import com.tbf.xml.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;


/**
 * SHIPMENTREQUEST class.
 */

public class SHIPMENTREQUEST

        implements com.tbf.xml.XmlObject, Validateable, java.io.Serializable {
private final static Logger log =  LogManager.getLogger();


    /**
     * Constant for "SHIPMENTDOCUMENTS" node name.
     */

    public static final String $SHIPMENTDOCUMENTS = "SHIPMENTDOCUMENTS";


    /**
     * Constant for "SORT" node name.
     */

    public static final String $SORT = "SORT";


    /**
     * Constant for "SHIPMENTREQUEST" node name.
     */

    public static final String $SHIPMENTREQUEST = "SHIPMENTREQUEST";


    /**
     * Constant for "DEFATTRIBUTES" node name.
     */

    public static final String $DEFATTRIBUTES = "DEFATTRIBUTES";


    /**
     * Constant for "PACKAGEDETAIL" node name.
     */

    public static final String $PACKAGEDETAIL = "PACKAGEDETAIL";


    /**
     * Constant for "LOGIN" node name.
     */

    public static final String $LOGIN = "LOGIN";


    /**
     * Constant for "CLOSEOUTMODE" node name.
     */

    public static final String $CLOSEOUTMODE = "CLOSEOUTMODE";


    /**
     * Constant for "PACKAGES" node name.
     */

    public static final String $PACKAGES = "PACKAGES";


    /**
     * Constant for "SHIPMENTSERVICE" node name.
     */

    public static final String $SHIPMENTSERVICE = "SHIPMENTSERVICE";


    protected LOGIN _LOGIN = null;

    protected DEFATTRIBUTES_1 _DEFATTRIBUTES = null;

    protected PACKAGES _PACKAGES = null;

    protected SHIPMENTSERVICE_1 _SHIPMENTSERVICE = null;

    protected SHIPMENTDOCUMENTS _SHIPMENTDOCUMENTS = null;

    protected String _CLOSEOUTMODE = null;

    protected String _PACKAGEDETAIL = null;

    protected String _SORT = null;


    /**
     * Storage for UNEXPECTED_XML errors.
     */

    protected Vector _unexpected_xml_errors_ = null;


    /**
     * Default no args constructor.
     */

    public SHIPMENTREQUEST() {

    }


    /**
     * Creates and populates an instance from the provided parse tree.
     *
     * @param xml the parse tree
     */

    public SHIPMENTREQUEST(XmlElement xml) {

        fromXml(xml);

    }


    /**
     * Get the LOGIN property.
     */

    public LOGIN getLOGIN() {

        return (_LOGIN);

    }


    /**
     * Set the LOGIN property.
     */

    public void setLOGIN(LOGIN obj) {

        _LOGIN = obj;

    }


    protected void setLOGIN(XmlElement xml) {


        _LOGIN =

                new LOGIN(xml);

    }


    /**
     * Checks for whether LOGIN is set or not.
     *
     * @returns true if LOGIN is set, false if not
     */

    public boolean hasLOGIN() {

        return (_LOGIN != null);

    }


    /**
     * Discards LOGIN's value.
     */

    public void deleteLOGIN() {

        _LOGIN = null;

    }


    /**
     * Get the DEFATTRIBUTES property.
     */

    public DEFATTRIBUTES_1 getDEFATTRIBUTES() {

        return (_DEFATTRIBUTES);

    }


    /**
     * Set the DEFATTRIBUTES property.
     */

    public void setDEFATTRIBUTES(DEFATTRIBUTES_1 obj) {

        _DEFATTRIBUTES = obj;

    }


    protected void setDEFATTRIBUTES(XmlElement xml) {


        _DEFATTRIBUTES =

                new DEFATTRIBUTES_1(xml);

    }


    /**
     * Checks for whether DEFATTRIBUTES is set or not.
     *
     * @returns true if DEFATTRIBUTES is set, false if not
     */

    public boolean hasDEFATTRIBUTES() {

        return (_DEFATTRIBUTES != null);

    }


    /**
     * Discards DEFATTRIBUTES's value.
     */

    public void deleteDEFATTRIBUTES() {

        _DEFATTRIBUTES = null;

    }


    /**
     * Get the PACKAGES property.
     */

    public PACKAGES getPACKAGES() {

        return (_PACKAGES);

    }


    /**
     * Set the PACKAGES property.
     */

    public void setPACKAGES(PACKAGES obj) {

        _PACKAGES = obj;

    }


    protected void setPACKAGES(XmlElement xml) {


        _PACKAGES =

                new PACKAGES(xml);

    }


    /**
     * Checks for whether PACKAGES is set or not.
     *
     * @returns true if PACKAGES is set, false if not
     */

    public boolean hasPACKAGES() {

        return (_PACKAGES != null);

    }


    /**
     * Discards PACKAGES's value.
     */

    public void deletePACKAGES() {

        _PACKAGES = null;

    }


    /**
     * Get the SHIPMENTSERVICE property.
     */

    public SHIPMENTSERVICE_1 getSHIPMENTSERVICE() {

        return (_SHIPMENTSERVICE);

    }


    /**
     * Set the SHIPMENTSERVICE property.
     */

    public void setSHIPMENTSERVICE(SHIPMENTSERVICE_1 obj) {

        _SHIPMENTSERVICE = obj;

    }


    protected void setSHIPMENTSERVICE(XmlElement xml) {


        _SHIPMENTSERVICE =

                new SHIPMENTSERVICE_1(xml);

    }


    /**
     * Checks for whether SHIPMENTSERVICE is set or not.
     *
     * @returns true if SHIPMENTSERVICE is set, false if not
     */

    public boolean hasSHIPMENTSERVICE() {

        return (_SHIPMENTSERVICE != null);

    }


    /**
     * Discards SHIPMENTSERVICE's value.
     */

    public void deleteSHIPMENTSERVICE() {

        _SHIPMENTSERVICE = null;

    }


    /**
     * Get the SHIPMENTDOCUMENTS property.
     */

    public SHIPMENTDOCUMENTS getSHIPMENTDOCUMENTS() {

        return (_SHIPMENTDOCUMENTS);

    }


    /**
     * Set the SHIPMENTDOCUMENTS property.
     */

    public void setSHIPMENTDOCUMENTS(SHIPMENTDOCUMENTS obj) {

        _SHIPMENTDOCUMENTS = obj;

    }


    protected void setSHIPMENTDOCUMENTS(XmlElement xml) {


        _SHIPMENTDOCUMENTS =

                new SHIPMENTDOCUMENTS(xml);

    }


    /**
     * Checks for whether SHIPMENTDOCUMENTS is set or not.
     *
     * @returns true if SHIPMENTDOCUMENTS is set, false if not
     */

    public boolean hasSHIPMENTDOCUMENTS() {

        return (_SHIPMENTDOCUMENTS != null);

    }


    /**
     * Discards SHIPMENTDOCUMENTS's value.
     */

    public void deleteSHIPMENTDOCUMENTS() {

        _SHIPMENTDOCUMENTS = null;

    }


    /**
     * Get the CLOSEOUTMODE property.
     */

    public String getCLOSEOUTMODE() {

        return (_CLOSEOUTMODE);

    }


    /**
     * Set the CLOSEOUTMODE property.
     */

    public void setCLOSEOUTMODE(String newValue) {

        _CLOSEOUTMODE = newValue;

    }


    /**
     * Checks for whether CLOSEOUTMODE is set or not.
     *
     * @returns true if CLOSEOUTMODE is set, false if not
     */

    public boolean hasCLOSEOUTMODE() {

        return (_CLOSEOUTMODE != null);

    }


    /**
     * Discards CLOSEOUTMODE's value.
     */

    public void deleteCLOSEOUTMODE() {

        _CLOSEOUTMODE = null;

    }


    /**
     * Get the PACKAGEDETAIL property.
     */

    public String getPACKAGEDETAIL() {

        return (_PACKAGEDETAIL);

    }


    /**
     * Set the PACKAGEDETAIL property.
     */

    public void setPACKAGEDETAIL(String newValue) {

        _PACKAGEDETAIL = newValue;

    }


    /**
     * Checks for whether PACKAGEDETAIL is set or not.
     *
     * @returns true if PACKAGEDETAIL is set, false if not
     */

    public boolean hasPACKAGEDETAIL() {

        return (_PACKAGEDETAIL != null);

    }


    /**
     * Discards PACKAGEDETAIL's value.
     */

    public void deletePACKAGEDETAIL() {

        _PACKAGEDETAIL = null;

    }


    /**
     * Get the SORT property.
     */

    public String getSORT() {

        return (_SORT);

    }


    /**
     * Set the SORT property.
     */

    public void setSORT(String newValue) {

        _SORT = newValue;

    }


    /**
     * Checks for whether SORT is set or not.
     *
     * @returns true if SORT is set, false if not
     */

    public boolean hasSORT() {

        return (_SORT != null);

    }


    /**
     * Discards SORT's value.
     */

    public void deleteSORT() {

        _SORT = null;

    }


    /**
     * Gets the XML tag name for this object.
     */

    public String getXmlTagName() {

        return ($SHIPMENTREQUEST);

    }


    /**
     * Gets the XML tag name for this class.
     */

    public static String getClassXmlTagName() {

        return ($SHIPMENTREQUEST);

    }


    /**
     * This flag is used to used to check whether
     * <p/>
     * the validators have been created.
     */

    transient protected static boolean _validators_created = false;



    /*

     * XML Validators

     */

    transient protected static XmlValidator

            _LOGIN_validator_ = null;

    transient protected static XmlValidator

            _DEFATTRIBUTES_validator_ = null;

    transient protected static XmlValidator

            _PACKAGES_validator_ = null;

    transient protected static XmlValidator

            _SHIPMENTSERVICE_validator_ = null;

    transient protected static XmlValidator

            _SHIPMENTDOCUMENTS_validator_ = null;

    transient protected static XmlStringValidator

            _PACKAGEDETAIL_validator_ = null;


    /**
     * Create the validators for this class.
     */

    protected static synchronized void createValidators() {


        if (_validators_created) {

            return;

        }


        _LOGIN_validator_ = new XmlValidator("SHIPMENTREQUEST.LOGIN", "Element",

                "SHIPMENTREQUEST/LOGIN", true);


        _DEFATTRIBUTES_validator_ = new XmlValidator("SHIPMENTREQUEST.DEFATTRIBUTES", "Element",

                "SHIPMENTREQUEST/DEFATTRIBUTES", true);


        _PACKAGES_validator_ = new XmlValidator("SHIPMENTREQUEST.PACKAGES", "Element",

                "SHIPMENTREQUEST/PACKAGES", true);


        _SHIPMENTSERVICE_validator_ = new XmlValidator("SHIPMENTREQUEST.SHIPMENTSERVICE", "Element",

                "SHIPMENTREQUEST/SHIPMENTSERVICE", true);


        _SHIPMENTDOCUMENTS_validator_ = new XmlValidator("SHIPMENTREQUEST.SHIPMENTDOCUMENTS", "Element",

                "SHIPMENTREQUEST/SHIPMENTDOCUMENTS", false);


        _PACKAGEDETAIL_validator_ = new XmlStringValidator("SHIPMENTREQUEST.PACKAGEDETAIL", "Element",

                "SHIPMENTREQUEST/PACKAGEDETAIL", -1, -1, true);


        _validators_created = true;

    }


    /**
     * Checks this object to see if it will produce valid XML.
     */

    public boolean isValid() {


        if (!(this instanceof Validateable)) {

            return (true);

        }


        Vector errors = ((Validateable) this).getValidationErrors(true);

        if (errors == null || errors.size() < 1) {

            return (true);

        }


        return (false);

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     */

    public Vector getValidationErrors() {

        return (getValidationErrors(false));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error) {

        return (getValidationErrors(return_on_error, true));

    }


    /**
     * Checks each field on the object for validity and
     * <p/>
     * returns a Vector holding the validation errors.
     *
     * @return a Vector containing the validation errors
     * @see com.tbf.xml.XmlValidationError
     */

    public Vector getValidationErrors(boolean return_on_error, boolean traverse) {


        createValidators();


        Vector errors;

        if (_unexpected_xml_errors_ != null &&

                _unexpected_xml_errors_.size() > 0) {

            errors = (Vector) _unexpected_xml_errors_.clone();

            if (return_on_error) {

                return (errors);

            }

        } else {

            errors = new Vector();

        }


        XmlValidationError e;

        e = _PACKAGEDETAIL_validator_.validate(_PACKAGEDETAIL);

        if (e != null) {

            errors.addElement(e);

            if (return_on_error) {

                return (errors);

            }

        }


        if (!traverse) {

            if (errors.size() < 1) {

                return (null);

            }


            return (errors);

        }


        boolean is_valid;


        is_valid = _LOGIN_validator_.isValid(_LOGIN,

                errors, return_on_error, traverse);

        if (!is_valid && return_on_error) {

            return (errors);

        }


        is_valid = _DEFATTRIBUTES_validator_.isValid(_DEFATTRIBUTES,

                errors, return_on_error, traverse);

        if (!is_valid && return_on_error) {

            return (errors);

        }


        is_valid = _PACKAGES_validator_.isValid(_PACKAGES,

                errors, return_on_error, traverse);

        if (!is_valid && return_on_error) {

            return (errors);

        }


        is_valid = _SHIPMENTSERVICE_validator_.isValid(_SHIPMENTSERVICE,

                errors, return_on_error, traverse);

        if (!is_valid && return_on_error) {

            return (errors);

        }


        is_valid = _SHIPMENTDOCUMENTS_validator_.isValid(_SHIPMENTDOCUMENTS,

                errors, return_on_error, traverse);

        if (!is_valid && return_on_error) {

            return (errors);

        }


        if (errors.size() < 1) {

            return (null);

        }


        return (errors);

    }


    /**
     * Checks the XML to see whether it matches the
     * <p/>
     * XML contents of this class.
     */

    public static boolean matches(XmlElement xml) {


        if (xml == null) {

            return (false);

        }


        return (xml.equals($SHIPMENTREQUEST));

    }


    /**
     * This method unmarshals an XML document instance
     * <p/>
     * into an instance of this class.
     */

    public static SHIPMENTREQUEST unmarshal(InputStream in) throws Exception {


        SHIPMENTREQUEST obj = new SHIPMENTREQUEST();

        ObjectFactory.unmarshal(obj, in);

        return (obj);

    }


    /**
     * Populates this object with the values from the
     * <p/>
     * parsed XML.
     */

    public void fromXml(XmlElement xml) {


        if (xml == null) {

            return;

        }


        if (!xml.equals($SHIPMENTREQUEST)) {

            return;

        }





        /*

         * Get the contained XmlElement, this is what we process

         */

        xml = xml.getSubElementAt(0);

        if (xml == null) {

            return;

        }


        if (xml.equals($LOGIN)) {

            setLOGIN(xml);

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($DEFATTRIBUTES)) {

            setDEFATTRIBUTES(xml);

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($PACKAGES)) {

            setPACKAGES(xml);

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($SHIPMENTSERVICE)) {

            setSHIPMENTSERVICE(xml);

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($SHIPMENTDOCUMENTS)) {

            setSHIPMENTDOCUMENTS(xml);

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($CLOSEOUTMODE)) {

            setCLOSEOUTMODE(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($PACKAGEDETAIL)) {

            setPACKAGEDETAIL(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml.equals($SORT)) {

            setSORT(xml.getData());

            xml = xml.next();

            if (xml == null) {

                return;

            }

        }


        if (xml != null) {


            _unexpected_xml_errors_ =

                    XmlValidationError.addUnexpectedXmlError(this, _unexpected_xml_errors_, xml);

            xml = xml.next();

        }

    }


    /**
     * This method marshals this object into an
     * <p/>
     * XML instance document.
     */

    public void marshal(OutputStream out) {

        toXml(out);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream) {

        toXml(stream, true);

    }


    /**
     * Serializes this object to Formatted XML.
     */

    public void toXml(OutputStream stream, String indent, boolean embed_files) {


        if (stream instanceof XmlOutputStream) {

            toXml(stream, embed_files);

        } else {

            FormattedOutputStream out =

                    new FormattedOutputStream(stream);

            out.setIndentString(indent);

            toXml(out, embed_files);

        }

    }


    /**
     * Serializes this object to XML.
     */

    public void toXml(OutputStream stream, boolean embed_files) {


        XmlOutputStream out = null;

        if (stream instanceof XmlOutputStream) {

            out = (XmlOutputStream) stream;

        } else {

            out = new RawOutputStream(stream);

        }


        out.writeStartTag(getXmlTagName(), false);

        out.incrementIndent();


        Object LOGIN_value = getLOGIN();

        if (LOGIN_value instanceof XmlObject) {

            out.write(null,

                    (XmlObject) LOGIN_value,

                    embed_files);

        }


        Object DEFATTRIBUTES_value = getDEFATTRIBUTES();

        if (DEFATTRIBUTES_value instanceof XmlObject) {

            out.write(null,

                    (XmlObject) DEFATTRIBUTES_value,

                    embed_files);

        }


        Object PACKAGES_value = getPACKAGES();

        if (PACKAGES_value instanceof XmlObject) {

            out.write(null,

                    (XmlObject) PACKAGES_value,

                    embed_files);

        }


        Object SHIPMENTSERVICE_value = getSHIPMENTSERVICE();

        if (SHIPMENTSERVICE_value instanceof XmlObject) {

            out.write(null,

                    (XmlObject) SHIPMENTSERVICE_value,

                    embed_files);

        }


        Object SHIPMENTDOCUMENTS_value = getSHIPMENTDOCUMENTS();

        if (SHIPMENTDOCUMENTS_value instanceof XmlObject) {

            out.write(null,

                    (XmlObject) SHIPMENTDOCUMENTS_value,

                    embed_files);

        }

        out.write($CLOSEOUTMODE,

                _CLOSEOUTMODE);

        out.write($PACKAGEDETAIL,

                _PACKAGEDETAIL);

        out.write($SORT,

                _SORT);


        out.decrementIndent();

        out.writeEndTag(getXmlTagName());

    }


    /**
     * Get the  birth certificate for this object.
     */

    public String birthCertificate() {

        return ("1hge137:cy11q2y1:s0zjo6");

    }

}
