
package com.owd.connectship.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CoreXmlPort", targetNamespace = "urn:connectship-com:ampcore")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CoreXmlPort {


    /**
     * Closes out a group of shipped packages.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.CloseOutResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "CloseOut")
    @WebResult(name = "closeOutResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public CloseOutResponse closeOut(
        @WebParam(name = "closeOutRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        CloseOutRequest body)
        throws ErrorMessage
    ;

    /**
     * Creates a new group using the specified data.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.CreateGroupResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "CreateGroup")
    @WebResult(name = "createGroupResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public CreateGroupResponse createGroup(
        @WebParam(name = "createGroupRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        CreateGroupRequest body)
        throws ErrorMessage
    ;

    /**
     * Performs a custom operation using the specified data.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.CustomOperationResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "CustomOperation")
    @WebResult(name = "customOperationResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public CustomOperationResponse customOperation(
        @WebParam(name = "customOperationRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        CustomOperationRequest body)
        throws ErrorMessage
    ;

    /**
     * Deletes a list of ship file items.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.DeleteShipFilesResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "DeleteShipFiles")
    @WebResult(name = "deleteShipFilesResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public DeleteShipFilesResponse deleteShipFiles(
        @WebParam(name = "deleteShipFilesRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        DeleteShipFilesRequest body)
        throws ErrorMessage
    ;

    /**
     * Deletes a list of transmit items.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.DeleteTransmitItemsResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "DeleteTransmitItems")
    @WebResult(name = "deleteTransmitItemsResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public DeleteTransmitItemsResponse deleteTransmitItems(
        @WebParam(name = "deleteTransmitItemsRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        DeleteTransmitItemsRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the detailed information about a group.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.GetGroupResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "GetGroup")
    @WebResult(name = "getGroupResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public GetGroupResponse getGroup(
        @WebParam(name = "getGroupRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        GetGroupRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available carriers.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListCarriersResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListCarriers")
    @WebResult(name = "listCarriersResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListCarriersResponse listCarriers(
        @WebParam(name = "listCarriersRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListCarriersRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available close out items.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListCloseOutItemsResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListCloseOutItems")
    @WebResult(name = "listCloseOutItemsResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListCloseOutItemsResponse listCloseOutItems(
        @WebParam(name = "listCloseOutItemsRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListCloseOutItemsRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available countries.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListCountriesResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListCountries")
    @WebResult(name = "listCountriesResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListCountriesResponse listCountries(
        @WebParam(name = "listCountriesRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListCountriesRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available currencies.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListCurrenciesResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListCurrencies")
    @WebResult(name = "listCurrenciesResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListCurrenciesResponse listCurrencies(
        @WebParam(name = "listCurrenciesRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListCurrenciesRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available documents.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListDocumentsResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListDocuments")
    @WebResult(name = "listDocumentsResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListDocumentsResponse listDocuments(
        @WebParam(name = "listDocumentsRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListDocumentsRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available formats for a document.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListDocumentFormatsResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListDocumentFormats")
    @WebResult(name = "listDocumentFormatsResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListDocumentFormatsResponse listDocumentFormats(
        @WebParam(name = "listDocumentFormatsRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListDocumentFormatsRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of supported groupings for a carrier.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListGroupingsResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListGroupings")
    @WebResult(name = "listGroupingsResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListGroupingsResponse listGroupings(
        @WebParam(name = "listGroupingsRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListGroupingsRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available groups for a grouping.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListGroupsResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListGroups")
    @WebResult(name = "listGroupsResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListGroupsResponse listGroups(
        @WebParam(name = "listGroupsRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListGroupsRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available Incoterms.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListIncotermsResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListIncoterms")
    @WebResult(name = "listIncotermsResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListIncotermsResponse listIncoterms(
        @WebParam(name = "listIncotermsRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListIncotermsRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of local printer ports.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListLocalPortsResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListLocalPorts")
    @WebResult(name = "listLocalPortsResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListLocalPortsResponse listLocalPorts(
        @WebParam(name = "listLocalPortsRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListLocalPortsRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available packaging types.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListPackagingTypesResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListPackagingTypes")
    @WebResult(name = "listPackagingTypesResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListPackagingTypesResponse listPackagingTypes(
        @WebParam(name = "listPackagingTypesRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListPackagingTypesRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available payment types.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListPaymentTypesResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListPaymentTypes")
    @WebResult(name = "listPaymentTypesResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListPaymentTypesResponse listPaymentTypes(
        @WebParam(name = "listPaymentTypesRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListPaymentTypesRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available printer devices.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListPrinterDevicesResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListPrinterDevices")
    @WebResult(name = "listPrinterDevicesResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListPrinterDevicesResponse listPrinterDevices(
        @WebParam(name = "listPrinterDevicesRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListPrinterDevicesRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available carrier services.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListServicesResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListServices")
    @WebResult(name = "listServicesResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListServicesResponse listServices(
        @WebParam(name = "listServicesRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListServicesRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available ship file items for a carrier and shipper.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListShipFilesResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListShipFiles")
    @WebResult(name = "listShipFilesResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListShipFilesResponse listShipFiles(
        @WebParam(name = "listShipFilesRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListShipFilesRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available shippers.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListShippersResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListShippers")
    @WebResult(name = "listShippersResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListShippersResponse listShippers(
        @WebParam(name = "listShippersRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListShippersRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available printer stocks.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListStocksResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListStocks")
    @WebResult(name = "listStocksResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListStocksResponse listStocks(
        @WebParam(name = "listStocksRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListStocksRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available transmit items for a carrier and shipper.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListTransmitItemsResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListTransmitItems")
    @WebResult(name = "listTransmitItemsResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListTransmitItemsResponse listTransmitItems(
        @WebParam(name = "listTransmitItemsRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListTransmitItemsRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of available units of measurement.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListUnitsResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListUnits")
    @WebResult(name = "listUnitsResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListUnitsResponse listUnits(
        @WebParam(name = "listUnitsRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListUnitsRequest body)
        throws ErrorMessage
    ;

    /**
     * Gets the list of printers configured through Windows.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ListWindowsPrintersResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ListWindowsPrinters")
    @WebResult(name = "listWindowsPrintersResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ListWindowsPrintersResponse listWindowsPrinters(
        @WebParam(name = "listWindowsPrintersRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ListWindowsPrintersRequest body)
        throws ErrorMessage
    ;

    /**
     * Modifies data for a previously saved container.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ModifyContainerResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ModifyContainer")
    @WebResult(name = "modifyContainerResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ModifyContainerResponse modifyContainer(
        @WebParam(name = "modifyContainerRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ModifyContainerRequest body)
        throws ErrorMessage
    ;

    /**
     * Modifies data and/or status for a group
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ModifyGroupResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ModifyGroup")
    @WebResult(name = "modifyGroupResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ModifyGroupResponse modifyGroup(
        @WebParam(name = "modifyGroupRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ModifyGroupRequest body)
        throws ErrorMessage
    ;

    /**
     * Modifies data and/or close out mode for a list of packages.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ModifyPackagesResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ModifyPackages")
    @WebResult(name = "modifyPackagesResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ModifyPackagesResponse modifyPackages(
        @WebParam(name = "modifyPackagesRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ModifyPackagesRequest body)
        throws ErrorMessage
    ;

    /**
     * Prints or saves a document.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.PrintResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "Print")
    @WebResult(name = "printResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public PrintResponse print(
        @WebParam(name = "printRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        PrintRequest body)
        throws ErrorMessage
    ;

    /**
     * Prints or saves a document from its XML representation.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.PrintXmlResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "PrintXml")
    @WebResult(name = "printXmlResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public PrintXmlResponse printXml(
        @WebParam(name = "printXmlRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        PrintXmlRequest body)
        throws ErrorMessage
    ;

    /**
     * Rates a list of packages using the specified services.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.RateResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "Rate")
    @WebResult(name = "rateResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public RateResponse rate(
        @WebParam(name = "rateRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        RateRequest body)
        throws ErrorMessage
    ;

    /**
     * Reprocesses a list of already shipped packages.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ReprocessResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "Reprocess")
    @WebResult(name = "reprocessResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ReprocessResponse reprocess(
        @WebParam(name = "reprocessRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ReprocessRequest body)
        throws ErrorMessage
    ;

    /**
     * Searches for packages based on the specified criteria
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.SearchResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "Search")
    @WebResult(name = "searchResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public SearchResponse search(
        @WebParam(name = "searchRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        SearchRequest body)
        throws ErrorMessage
    ;

    /**
     * Ships a list of packages using the specified service.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ShipResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "Ship")
    @WebResult(name = "shipResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ShipResponse ship(
        @WebParam(name = "shipRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ShipRequest body)
        throws ErrorMessage
    ;

    /**
     * Transmits or offloads a list of transmit items.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.TransmitResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "Transmit")
    @WebResult(name = "transmitResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public TransmitResponse transmit(
        @WebParam(name = "transmitRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        TransmitRequest body)
        throws ErrorMessage
    ;

    /**
     * Validates the specified address.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.ValidateAddressResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "ValidateAddress")
    @WebResult(name = "validateAddressResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public ValidateAddressResponse validateAddress(
        @WebParam(name = "validateAddressRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        ValidateAddressRequest body)
        throws ErrorMessage
    ;

    /**
     * Voids a list of shipped packages.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.VoidPackagesResponse
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "VoidPackages")
    @WebResult(name = "voidPackagesResponse", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public VoidPackagesResponse voidPackages(
        @WebParam(name = "voidPackagesRequest", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        VoidPackagesRequest body)
        throws ErrorMessage
    ;

    /**
     * Executes a list of operations in a single request.
     * 
     * @param body
     * @return
     *     returns com.owd.connectship.soap.CompoundResult
     * @throws ErrorMessage
     */
    @WebMethod(operationName = "Compound")
    @WebResult(name = "compoundResult", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
    public CompoundResult compound(
        @WebParam(name = "compoundOperation", targetNamespace = "urn:connectship-com:ampcore", partName = "body")
        CompoundOperation body)
        throws ErrorMessage
    ;

}
