package com.owd.jobs.jobobjects.paypal;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * SubscriptionInfoType
 * Information about a PayPal Subscription.
 * <p/>
 * <p/>
 * <p>Java class for SubscriptionInfoType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="SubscriptionInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
private final static Logger log =  LogManager.getLogger();
 *       &lt;sequence>
 *         &lt;element ref="{urn:ebay:apis:eBLBaseComponents}SubscriptionID"/>
 *         &lt;element name="SubscriptionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="EffectiveDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="RetryTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Username" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Recurrences" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Terms" type="{urn:ebay:apis:eBLBaseComponents}SubscriptionTermsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="reattempt" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="recurring" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscriptionInfoType", namespace = "urn:ebay:apis:eBLBaseComponents", propOrder = {
        "subscriptionID",
        "subscriptionDate",
        "effectiveDate",
        "retryTime",
        "username",
        "password",
        "recurrences",
        "terms"
})
public class SubscriptionInfoType
{

    @XmlElement(name = "SubscriptionID", namespace = "urn:ebay:apis:eBLBaseComponents", required = true)
    protected String subscriptionID;
    @XmlElement(name = "SubscriptionDate", namespace = "urn:ebay:apis:eBLBaseComponents")
    protected XMLGregorianCalendar subscriptionDate;
    @XmlElement(name = "EffectiveDate", namespace = "urn:ebay:apis:eBLBaseComponents")
    protected XMLGregorianCalendar effectiveDate;
    @XmlElement(name = "RetryTime", namespace = "urn:ebay:apis:eBLBaseComponents")
    protected XMLGregorianCalendar retryTime;
    @XmlElement(name = "Username", namespace = "urn:ebay:apis:eBLBaseComponents")
    protected String username;
    @XmlElement(name = "Password", namespace = "urn:ebay:apis:eBLBaseComponents")
    protected String password;
    @XmlElement(name = "Recurrences", namespace = "urn:ebay:apis:eBLBaseComponents")
    protected String recurrences;
    @XmlElement(name = "Terms", namespace = "urn:ebay:apis:eBLBaseComponents")
    protected List<SubscriptionTermsType> terms;
    @XmlAttribute(required = true)
    protected String reattempt;
    @XmlAttribute(required = true)
    protected String recurring;

    /**
     * ID generated by PayPal for the subscriber.
     * Character length and limitations: no limit
     *
     * @return possible object is
     *         {@link String }
     */
    public String getSubscriptionID()
    {
        return subscriptionID;
    }

    /**
     * ID generated by PayPal for the subscriber.
     * Character length and limitations: no limit
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSubscriptionID(String value)
    {
        this.subscriptionID = value;
    }

    /**
     * Gets the value of the subscriptionDate property.
     *
     * @return possible object is
     *         {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getSubscriptionDate()
    {
        return subscriptionDate;
    }

    /**
     * Sets the value of the subscriptionDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setSubscriptionDate(XMLGregorianCalendar value)
    {
        this.subscriptionDate = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     *
     * @return possible object is
     *         {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getEffectiveDate()
    {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setEffectiveDate(XMLGregorianCalendar value)
    {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the retryTime property.
     *
     * @return possible object is
     *         {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getRetryTime()
    {
        return retryTime;
    }

    /**
     * Sets the value of the retryTime property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setRetryTime(XMLGregorianCalendar value)
    {
        this.retryTime = value;
    }

    /**
     * Gets the value of the username property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getUsername()
    {
        return username;
    }

    /**
     * Sets the value of the username property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUsername(String value)
    {
        this.username = value;
    }

    /**
     * Gets the value of the password property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPassword()
    {
        return password;
    }

    /**
     * Sets the value of the password property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPassword(String value)
    {
        this.password = value;
    }

    /**
     * Gets the value of the recurrences property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getRecurrences()
    {
        return recurrences;
    }

    /**
     * Sets the value of the recurrences property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRecurrences(String value)
    {
        this.recurrences = value;
    }

    /**
     * Gets the value of the terms property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the terms property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTerms().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link SubscriptionTermsType }
     */
    public List<SubscriptionTermsType> getTerms()
    {
        if (terms == null)
        {
            terms = new ArrayList<SubscriptionTermsType>();
        }
        return this.terms;
    }

    /**
     * Gets the value of the reattempt property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getReattempt()
    {
        return reattempt;
    }

    /**
     * Sets the value of the reattempt property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReattempt(String value)
    {
        this.reattempt = value;
    }

    /**
     * Gets the value of the recurring property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getRecurring()
    {
        return recurring;
    }

    /**
     * Sets the value of the recurring property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRecurring(String value)
    {
        this.recurring = value;
    }

}
